[default]
Integer_min = 0
Integer_max = 100

String_max = 10

Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 2
Snapshot_max = 2
# Filmstrip
Filmstrip_min = 1
Filmstrip_max = 1
# System
System_min = 2
System_max = 2
# Application
Application_min = 4
Application_max = 4

### Class Properties
# System - free_memory
System_freeMemory_min = 0
System_freeMemory_max = 15
#System_freeMemory: Set{10}
System_loadedAppIds_min = -1
System_loadedAppIds_max = -1
#System_loadedAppIds: Set{1, 2}
System_installedAppIds_min = -1
System_installedAppIds_max = -1
#System_installedAppIds: Set{1, 2}
# Application - size
#Application_size_min = 1
#Application_size_max = 5
Application_size: Set{1, 2, 3, 4, 5}
Application_id: Set{1, 2}

### Operation Classes
# load_SystemOpC
load_SystemOpC_min = 1
load_SystemOpC_max = 1
# install_SystemOpC
install_SystemOpC_min = 0
install_SystemOpC_max = 0
# run_SystemOpC
run_SystemOpC_min = 0
run_SystemOpC_max = 0

### Association
# SnapshotSystem
SnapshotSystem_min = 2
SnapshotSystem_max = 2
# SnapshotApplication
SnapshotApplication_min = 4
SnapshotApplication_max = 4
# PredSucc System
PredSuccSystem_min = 1
PredSuccSystem_max = 1
# PredSucc Application
PredSuccApplication_min = 2
PredSuccApplication_max = 2


aggregationcyclefreeness = on
forbiddensharing = on