package org.vnu.sme.goal.acl.mm;

import java.util.*;

/** Semantic rules from ACL_doc.md that cannot be encoded by multiplicities alone. */
public final class AclSemanticValidator {
    private AclSemanticValidator(){}
    public static List<String> validate(AclModel m){
        List<String> e=new ArrayList<>(); Map<String,String> kinds=new LinkedHashMap<>();
        m.entities().forEach(x->unique(kinds,x.name(),"Entity",e)); m.roles().forEach(x->unique(kinds,x.name(),"Role",e)); m.groups().forEach(x->unique(kinds,x.name(),"Group",e));
        Map<String,AclRole> roles=new HashMap<>();m.roles().forEach(x->roles.put(x.name(),x)); Set<String> entities=new HashSet<>();m.entities().forEach(x->entities.add(x.name())); Set<String> groups=new HashSet<>();m.groups().forEach(x->groups.add(x.name()));
        validateGeneralizations(m.generalizations(),kinds,e); validateRelations(m.relations(),entities,kinds.keySet(),e); validateOwners(m.owners(),roles,groups,e); validateCompatibility(m.compatibilities(),roles,e);
        return List.copyOf(e);
    }
    private static void validateGeneralizations(List<AclGeneralization> gs,Map<String,String> kinds,List<String> e){ Map<String,String>parent=new HashMap<>(); for(var g:gs){String sk=kinds.get(g.specific()),gk=kinds.get(g.general());if(sk==null||gk==null)e.add("generalization references unknown classifier");else if(!sk.equals(gk)||sk.equals("Group"))e.add("generalization '"+g.specific()+" -> "+g.general()+"' must connect Entity-to-Entity or Role-to-Role");if(g.specific().equals(g.general()))e.add("classifier cannot specialize itself");if(parent.putIfAbsent(g.specific(),g.general())!=null)e.add("classifier '"+g.specific()+"' has more than one general");} for(String n:parent.keySet()){Set<String>p=new HashSet<>();String x=n;while(x!=null){if(!p.add(x)){e.add("generalization cycle involving '"+x+"'");break;}x=parent.get(x);}} }
    private static void validateRelations(List<AclRelation> rs,Set<String> entities,Set<String> classifiers,List<String> e){Set<String>names=new HashSet<>(),compositeParts=new HashSet<>();Map<String,String>comp=new HashMap<>();for(var r:rs){if(!names.add(r.name()))e.add("duplicate relationship '"+r.name()+"'");if(!classifiers.contains(r.source().type())||!classifiers.contains(r.target().type()))e.add("relationship '"+r.name()+"' references unknown endpoint type");if(!entities.contains(r.source().type())&&!entities.contains(r.target().type()))e.add("relationship '"+r.name()+"' must have at least one Entity endpoint");if(r.kind()==RelationKind.COMPOSITION){if(!compositeParts.add(r.target().type()))e.add("classifier '"+r.target().type()+"' has more than one composite owner");comp.put(r.source().type(),r.target().type());}} for(String n:comp.keySet()){Set<String>p=new HashSet<>();String x=n;while(x!=null){if(!p.add(x)){e.add("composition cycle involving '"+x+"'");break;}x=comp.get(x);}}}
    private static void validateOwners(List<AclOwner> os,Map<String,AclRole> roles,Set<String> groups,List<String> e){Map<String,List<String>>graph=new HashMap<>();Set<String>parts=new HashSet<>();for(var o:os){if(!groups.contains(o.sourceGroup()))e.add("Owner source '"+o.sourceGroup()+"' must be a Group");boolean role=roles.containsKey(o.target()),group=groups.contains(o.target());if(!role&&!group)e.add("Owner target '"+o.target()+"' must be Role or Group");if(role&&roles.get(o.target()).isAbstract())e.add("abstract Role '"+o.target()+"' cannot be owned by Group");if(!parts.add(o.target()))e.add("'"+o.target()+"' has more than one Owner");if(group)graph.computeIfAbsent(o.sourceGroup(),k->new ArrayList<>()).add(o.target());}for(String n:graph.keySet())ownerCycle(n,graph,new HashSet<>(),e);}
    private static void ownerCycle(String n,Map<String,List<String>>g,Set<String>path,List<String>e){if(!path.add(n)){e.add("Owner cycle involving Group '"+n+"'");return;}for(String c:g.getOrDefault(n,List.of()))ownerCycle(c,g,path,e);path.remove(n);}
    private static void validateCompatibility(List<AclCompatibility> cs,Map<String,AclRole>roles,List<String>e){Set<String>seen=new HashSet<>();for(var c:cs){if(!roles.containsKey(c.fromRole())||!roles.containsKey(c.toRole()))e.add("Compatibility endpoints must both be Roles");String a=c.fromRole().compareTo(c.toRole())<=0?c.fromRole():c.toRole(),b=a.equals(c.fromRole())?c.toRole():c.fromRole();if(!seen.add(a+"\0"+b))e.add("duplicate Compatibility between '"+a+"' and '"+b+"'");}}
    private static void unique(Map<String,String>m,String n,String k,List<String>e){String old=m.putIfAbsent(n,k);if(old!=null)e.add("duplicate classifier name '"+n+"' (already "+old+")");}
}
