[default]
Integer_min = 1
Integer_max = 3

String_max = 10

Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 6
Snapshot_max = 6
# Filmstrip
Filmstrip_min = 5
Filmstrip_max = 5
# Elevator
Elevator_min = 6
Elevator_max = 6
# FloorButton
FloorButton_min = 12
FloorButton_max = 12

### Class Properties
# FloorButton
FloorButton_floor_min = 1
FloorButton_floor_max = 3
# Elevator
Elevator_currentFloor_min = 1
Elevator_currentFloor_max = 3
Elevator_targetFloor_min = 1
Elevator_targetFloor_max = 3

### Operation Classes
# press_FloorButtonOpC
press_FloorButtonOpC_min = 1
press_FloorButtonOpC_max = 1
# move_ElevatorOpC
move_ElevatorOpC_min = 1
move_ElevatorOpC_max = 1
# openDoor_ElevatorOpC
openDoor_ElevatorOpC_min = 1
openDoor_ElevatorOpC_max = 1
# addTargetFloor_ElevatorOpC
addTargetFloor_ElevatorOpC_min = 1
addTargetFloor_ElevatorOpC_max = 1
# closeDoor_ElevatorOpC
closeDoor_ElevatorOpC_min = 1
closeDoor_ElevatorOpC_max = 1

### Association
# ElevatorButton
ElevatorButton_min = 12
ElevatorButton_max = 12
# SnapshotElevator
SnapshotElevator_min = 6
SnapshotElevator_max = 6
# SnapshotFloorButton
SnapshotFloorButton_min = 12
SnapshotFloorButton_max = 12
# PredSuccElevator
PredSuccElevator_min = 5
PredSuccElevator_max = 5
# PredSuccFloorButton
PredSuccFloorButton_min = 10
PredSuccFloorButton_max = 10

### Others
aggregationcyclefreeness = on
forbiddensharing = on