[default]
Integer_min = 1
Integer_max = 3

String_max = 10

Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 9
Snapshot_max = 9
# Filmstrip
Filmstrip_min = 8
Filmstrip_max = 8
# Elevator
Elevator_min = 9
Elevator_max = 9
# FloorButton
FloorButton_min = 18
FloorButton_max = 18

### Class Properties
# FloorButton
FloorButton_floor_min = 1
FloorButton_floor_max = 2
# Elevator
Elevator_currentFloor_min = 1
Elevator_currentFloor_max = 2
Elevator_targetFloor_min = 1
Elevator_targetFloor_max = 2

### Operation Classes
# press_FloorButtonOpC
press_FloorButtonOpC_min = 2
press_FloorButtonOpC_max = 2
# move_ElevatorOpC
move_ElevatorOpC_min = 2
move_ElevatorOpC_max = 2
# openDoor_ElevatorOpC
openDoor_ElevatorOpC_min = 2
openDoor_ElevatorOpC_max = 2
# closeDoor_ElevatorOpC
closeDoor_ElevatorOpC_min = 2
closeDoor_ElevatorOpC_max = 2

### Association
# ElevatorButton
ElevatorButton_min = 18
ElevatorButton_max = 18
# SnapshotElevator
SnapshotElevator_min = 9
SnapshotElevator_max = 9
# SnapshotFloorButton
SnapshotFloorButton_min = 18
SnapshotFloorButton_max = 18
# PredSuccElevator
PredSuccElevator_min = 8
PredSuccElevator_max = 8
# PredSuccFloorButton
PredSuccFloorButton_min = 16
PredSuccFloorButton_max = 16

### Others
aggregationcyclefreeness = on
forbiddensharing = on