[default]
Integer_min = 1
Integer_max = 3

String_max = 10

Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 5
Snapshot_max = 5
# Filmstrip
Filmstrip_min = 4
Filmstrip_max = 4
# Elevator
Elevator_min = 5
Elevator_max = 5
# FloorButton
FloorButton_min = 5
FloorButton_max = 5

### Class Properties
# FloorButton
FloorButton_floor_min = 1
FloorButton_floor_max = 3
# Elevator
Elevator_currentFloor_min = 1
Elevator_currentFloor_max = 3
Elevator_targetFloor_min = 1
Elevator_targetFloor_max = 3

### Operation Classes
# press_FloorButtonOpC
press_FloorButtonOpC_min = 1
press_FloorButtonOpC_max = 1
# move_ElevatorOpC
move_ElevatorOpC_min = 1
move_ElevatorOpC_max = 1
# openDoor_ElevatorOpC
openDoor_ElevatorOpC_min = 1
openDoor_ElevatorOpC_max = 1
# addTargetFloor_ElevatorOpC
addTargetFloor_ElevatorOpC_min = 1
addTargetFloor_ElevatorOpC_max = 1
# closeDoor_ElevatorOpC
closeDoor_ElevatorOpC_min = 0
closeDoor_ElevatorOpC_max = 0

### Association
# ElevatorButton
ElevatorButton_min = 5
ElevatorButton_max = 5
# SnapshotElevator
SnapshotElevator_min = 5
SnapshotElevator_max = 5
# SnapshotFloorButton
SnapshotFloorButton_min = 5
SnapshotFloorButton_max = 5
# PredSuccElevator
PredSuccElevator_min = 4
PredSuccElevator_max = 4
# PredSuccFloorButton
PredSuccFloorButton_min = 4
PredSuccFloorButton_max = 4

### Others
aggregationcyclefreeness = on
forbiddensharing = on