[default]
Integer_min = 0
Integer_max = 100

String_max = 10

Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 4
Snapshot_max = 4
# Filmstrip
Filmstrip_min = 3
Filmstrip_max = 3
# System
System_min = 4
System_max = 4
# Application
Application_min = 8
Application_max = 8

### Class Properties
# System - free_memory
System_freeMemory_min = 0
System_freeMemory_max = 15
#System_freeMemory: Set{10}
System_loadedAppIds_min = -1
System_loadedAppIds_max = -1
System_loadedAppIds: Set{1, 2}
System_installedAppIds_min = -1
System_installedAppIds_max = -1
System_installedAppIds: Set{1, 2}
# Application - size
#Application_size_min = 1
#Application_size_max = 5
Application_size: Set{1, 2, 3}
Application_id: Set{1, 2}

### Operation Classes
# load_SystemOpC
load_SystemOpC_min = 1
load_SystemOpC_max = 1
# install_SystemOpC
install_SystemOpC_min = 1
install_SystemOpC_max = 1
# run_SystemOpC
run_SystemOpC_min = 1
run_SystemOpC_max = 1

### Association
# SnapshotSystem
SnapshotSystem_min = 4
SnapshotSystem_max = 4
# SnapshotApplication
SnapshotApplication_min = 8
SnapshotApplication_max = 8
# PredSucc System
PredSuccSystem_min = 3
PredSuccSystem_max = 3
# PredSucc Application
PredSuccApplication_min = 6
PredSuccApplication_max = 6


aggregationcyclefreeness = on
forbiddensharing = on