<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd ">
	<!-- The basics	-->
	<modelVersion>4.0.0</modelVersion>
	<artifactId>tocl</artifactId>
	<parent>
		<artifactId>use</artifactId>
		<groupId>org.tzi.use</groupId>
		<version>7.1.1</version>
	</parent>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>use-core</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>use-gui</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>antlr4-runtime</artifactId>
			<version>4.9.3</version>
		</dependency>
		<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>antlr4-maven-plugin</artifactId>
			<version>4.9.3</version>
		</dependency>
		<dependency>
			<groupId>org.tzi.use</groupId>
			<artifactId>filmstrip</artifactId>
			<version>7.1.1</version>
		</dependency>
	</dependencies>
	<packaging>jar</packaging>

	<!-- Build settings	-->
	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<release>21</release>
<!--					<generatedSourcesDirectory>${project.build.directory}/generated-sources/antlr3</generatedSourcesDirectory>-->
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.2</version>
				<configuration>
					<archive>
						<manifestFile>src/main/resources/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.bekioui.maven.plugin</groupId>
				<artifactId>merge-maven-plugin</artifactId>
				<version>1.2.0</version>
				<executions>
					<execution>
						<id>merge-grammar-files</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>merge</goal>
						</goals>
						<configuration>
							<merges>
								<merge>
									<target>${project.build.directory}/grammars/TOCL.g4</target>
									<sources>
										<source>src/main/resources/grammars/TOCL.g4</source>
									</sources>
									<override>true</override>
								</merge>
							</merges>
						</configuration>
					</execution>
				</executions>
			</plugin>
<!--			Currently using Antlr4 -->
			<plugin>
<!--				<groupId>org.antlr</groupId>-->
<!--				<artifactId>antlr3-maven-plugin</artifactId>-->
<!--				<version>3.5.3</version>-->
<!--				<configuration>-->
<!--					<report>false</report>-->
<!--					<trace>false</trace>-->
<!--					<nfa>false</nfa>-->
<!--					<dfa>false</dfa>-->
<!--					<sourceDirectory>${project.build.directory}/grammars</sourceDirectory>-->
<!--					<outputDirectory>${project.build.directory}/generated-sources/antlr3</outputDirectory>-->
<!--					<verbose>false</verbose>-->
<!--				</configuration>-->
				<groupId>org.antlr</groupId>
				<artifactId>antlr4-maven-plugin</artifactId>
				<version>4.9.3</version>
				<configuration>
					<sourceDirectory>${project.build.directory}/grammars</sourceDirectory>
					<outputDirectory>${project.build.directory}/generated-sources/antlr4</outputDirectory>
				</configuration>
				<executions>
					<execution>
						<id>antlr</id>
						<phase>generate-sources</phase>
						<goals>
<!--							<goal>antlr</goal>-->
							<goal>antlr4</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!--	move generated lexer and parser 	-->
			<plugin>
				<groupId>com.coderplus.maven.plugins</groupId>
				<artifactId>copy-rename-maven-plugin</artifactId>
				<version>1.0</version>
				<executions>
					<execution>
						<id>move-antlr-parser-use</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>rename</goal>
						</goals>
						<configuration>
							<fileSets>
<!--								<fileSet>-->
<!--									<sourceFile>target/generated-sources/antlr3/TOCLLexer.java</sourceFile>-->
<!--									<destinationFile>target/generated-sources/antlr3/org/vnu/sme/tocl/parser/TOCLLexer.java</destinationFile>-->
<!--								</fileSet>-->
<!--								<fileSet>-->
<!--									<sourceFile>target/generated-sources/antlr3/TOCLParser.java</sourceFile>-->
<!--									<destinationFile>target/generated-sources/antlr3/org/vnu/sme/tocl/parser/TOCLParser.java</destinationFile>-->
<!--								</fileSet>-->
								<fileSet>
									<sourceFile>target/generated-sources/antlr4/TOCLLexer.java</sourceFile>
									<destinationFile>target/generated-sources/antlr4/org/vnu/sme/tocl/parser/TOCLLexer.java</destinationFile>
								</fileSet>
								<fileSet>
									<sourceFile>target/generated-sources/antlr4/TOCLParser.java</sourceFile>
									<destinationFile>target/generated-sources/antlr4/org/vnu/sme/tocl/parser/TOCLParser.java</destinationFile>
								</fileSet>
								<fileSet>
									<sourceFile>target/generated-sources/antlr4/TOCLListener.java</sourceFile>
									<destinationFile>target/generated-sources/antlr4/org/vnu/sme/tocl/parser/TOCLListener.java</destinationFile>
								</fileSet>
								<fileSet>
									<sourceFile>target/generated-sources/antlr4/TOCLBaseListener.java</sourceFile>
									<destinationFile>target/generated-sources/antlr4/org/vnu/sme/tocl/parser/TOCLBaseListener.java</destinationFile>
								</fileSet>
							</fileSets>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- this makes a fat jar with all dependencies -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.6.0</version>
				<executions>
					<execution>
						<phase>package</phase>
<!--						<phase>install</phase>-->
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<minimizeJar>false</minimizeJar>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>complete</shadedClassifierName>
							<filters>
								<filter>
									<artifact>*:antlr4-runtime</artifact>
									<includes>
										<include>org/antlr/**</include>
									</includes>
								</filter>
								<filter>
									<artifact>*:filmstrip</artifact>
									<includes>
										<include>org/tzi/use/**</include>
									</includes>
								</filter>
							</filters>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- Add the maven-antrun-plugin to move the JAR file to USE plugins folder -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<id>copy-jar</id>
<!--						<phase>install</phase>-->
						<phase>package</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
<!--								<copy file="${project.build.directory}/${project.build.finalName}.jar"-->
<!--									  tofile="../use/use-assembly/target/use-7.1.1/lib/plugins/${project.build.finalName}.jar"-->
<!--								      overwrite="true"/>-->
								<copy file="${project.build.directory}/${project.build.finalName}-complete.jar"
									  tofile="../use-main/use-assembly/target/extracted/use-7.1.1/lib/plugins/${project.build.finalName}-complete.jar"
									  overwrite="true"/>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<!-- More project information -->
	<name>TemporalOCL Plugin</name>
	<description>An OCL extension to specify temporal properties in USE tool</description>
	<inceptionYear>2024</inceptionYear>
	<organization>
		<name>VNU-SME lab</name>
		<url>to-do: update lab's website</url>
	</organization>
	<developers>
		<developer>
			<name>Hai Dinh Minh</name>
			<email>domohai12@gmail.com</email>
			<url>https://domohai.github.io/domohai/</url>
		</developer>
	</developers>
</project>
