<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:sTM="http://www.example.org/sTM">
  <ecore:EPackage name="sTM" nsURI="http://www.example.org/sTM" nsPrefix="sTM">
    <eAnnotations source="http://www.eclipse.org/OCL/Import">
      <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="SnapshotClassifier" eSuperTypes="#/0/Classifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="UniqueIds AcyclicScenario OneScenario SameSnapshot"/>
      </eAnnotations>
      <eOperations name="getNext" eType="#/0/SnapshotClassifier"/>
      <eOperations name="getPost" ordered="false" upperBound="-1" eType="#/0/SnapshotClassifier"/>
      <eOperations name="getPrevious" eType="#/0/SnapshotClassifier"/>
      <eOperations name="getPre" ordered="false" upperBound="-1" eType="#/0/SnapshotClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="snapshotObjects" upperBound="-1"
          eType="#/0/SnapshotComponent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nextT" eType="#/0/TransitionClass"
          eOpposite="#/0/TransitionClass/beforeS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="beforeT" eType="#/0/TransitionClass"
          eOpposite="#/0/TransitionClass/nextS"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFirst" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLast" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransitionClass" eSuperTypes="#/0/NamedElement #/0/Classifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="SameTrans"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#/0/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#/0/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#/0/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isParentClass" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitionParent" lowerBound="1"
          eType="#/0/TransitionClass" eOpposite="#/0/TransitionClass/transitionSubClasses"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitionSubClasses"
          upperBound="-1" eType="#/0/TransitionClass" eOpposite="#/0/TransitionClass/transitionParent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="beforeS" lowerBound="1"
          eType="#/0/SnapshotClassifier" eOpposite="#/0/SnapshotClassifier/nextT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nextS" lowerBound="1"
          eType="#/0/SnapshotClassifier" eOpposite="#/0/SnapshotClassifier/beforeT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="postObjects" upperBound="-1"
          eType="#/0/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SnapshotComponent" eSuperTypes="#/0/Classifier">
      <eOperations name="getNext" eType="#/0/SnapshotComponent"/>
      <eOperations name="getPost" ordered="false" upperBound="-1" eType="#/0/SnapshotComponent"/>
      <eOperations name="getPrevious" eType="#/0/SnapshotComponent"/>
      <eOperations name="getPre" ordered="false" upperBound="-1" eType="#/0/SnapshotComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#/0/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#/0/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="queryOperations" upperBound="-1"
          eType="#/0/Operation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#/0/TypedElement #/0/Classifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEnd" upperBound="-1"
          eType="#/0/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memberEnd" lowerBound="2"
          upperBound="-1" eType="#/0/Property" eOpposite="#/0/Property/association"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
          eType="#/0/ValueSpecification" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#/0/NamedElement #/0/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="association" eType="#/0/Association"
          eOpposite="#/0/Association/memberEnd"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedProperty" upperBound="-1"
          eType="#/0/Property"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="#/0/AggregationKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typedElement" upperBound="-1"
          eType="#/0/TypedElement" eOpposite="#/0/TypedElement/type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          upperBound="-1" eType="#/0/Type" eOpposite="#/0/Type/typedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#/0/Classifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
          eType="#/0/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
          eType="#/0/Operation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#/0/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiteral" upperBound="-1"
          eType="#/0/EnumerationLiteral" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumerationLiteral" upperBound="-1"
          eType="#/0/EnumerationLiteral" eOpposite="#/0/EnumerationLiteral/enumeration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" lowerBound="1"
          eType="#/0/Enumeration" eOpposite="#/0/Enumeration/enumerationLiteral"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/0/Type"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#/0/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodyCondition" upperBound="-1"
          eType="#/0/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="postcondition" upperBound="-1"
          eType="#/0/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" upperBound="-1"
          eType="#/0/Constraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="#/0/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" upperBound="-1"
          eType="#/0/Generalization" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Generalization">
      <eStructuralFeatures xsi:type="ecore:EReference" name="general" eType="#/0/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpaqueExpression" eSuperTypes="#/0/ValueSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#/0/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/ocl/2015/Pivot#T-pivot-String"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true"
        eSuperTypes="#/0/TypedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralSpecification" abstract="true"
        eSuperTypes="#/0/ValueSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralInteger" eSuperTypes="#/0/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/ocl/2015/Pivot#T-pivot-Integer"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralUnlimitedNatural" eSuperTypes="#/0/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/ocl/2015/Pivot#T-pivot-UnlimitedNatural"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralReal" eSuperTypes="#/0/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/ocl/2015/Pivot#T-pivot-Real"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralString" eSuperTypes="#/0/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralNull" eSuperTypes="#/0/LiteralSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralBoolean">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SnapshotAssocClass" eSuperTypes="#/0/Association #/0/SnapshotComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" upperBound="-1"
          eType="#/0/NamedElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AggregationKind">
      <eLiterals name="none"/>
      <eLiterals name="shared"/>
      <eLiterals name="composite"/>
    </eClassifiers>
  </ecore:EPackage>
  <sTM:Model name="SteamBoilerSTM">
    <ownedElements xsi:type="sTM:SnapshotClassifier" name="Snapshot">
      <snapshotObjects name="WaterLevelMeasurementDevice" typedElement="#/1/@ownedElements.18/@context #/1/@ownedElements.4/@ownedEnd.1 #/1/@ownedElements.10/@ownedEnd.1">
        <attributes name="waterLevel" type="#/1/@ownedElements.22" lower="1" upper="1"/>
        <constraints name="WaterLevelLimit">
          <specification xsi:type="sTM:OpaqueExpression">
            <body>(self.waterLevel &lt;= self.sb.capacity)</body>
          </specification>
        </constraints>
      </snapshotObjects>
      <snapshotObjects name="ControlProgram" typedElement="#/1/@ownedElements.17/@context #/1/@ownedElements.8/@ownedEnd.0 #/1/@ownedElements.4/@ownedEnd.0 #/1/@ownedElements.7/@ownedEnd.0 #/1/@ownedElements.9/@ownedEnd.0 #/1/@ownedElements.3/@ownedEnd.1">
        <attributes name="failureDetected" type="#/1/@ownedElements.23" lower="1"
            upper="1"/>
        <attributes name="mode" type="#/1/@ownedElements.13" lower="1" upper="1"/>
        <attributes name="pumpControllerFailure" type="#/1/@ownedElements.23" lower="1"
            upper="1"/>
        <attributes name="pumpFailure" type="#/1/@ownedElements.23" lower="1" upper="1"/>
        <attributes name="ready" type="#/1/@ownedElements.23" lower="1" upper="1"/>
        <attributes name="smdFailure" type="#/1/@ownedElements.23" lower="1" upper="1"/>
        <attributes name="wlmdFailure" type="#/1/@ownedElements.23" lower="1" upper="1"/>
      </snapshotObjects>
      <snapshotObjects name="PumpController" typedElement="#/1/@ownedElements.19/@context #/1/@ownedElements.20/@context #/1/@ownedElements.8/@ownedEnd.1 #/1/@ownedElements.5/@ownedEnd.0">
        <attributes name="circulating" type="#/1/@ownedElements.23" lower="1" upper="1"/>
      </snapshotObjects>
      <snapshotObjects name="SteamBoiler" typedElement="#/1/@ownedElements.21/@context #/1/@ownedElements.11/@ownedEnd.0 #/1/@ownedElements.10/@ownedEnd.0 #/1/@ownedElements.3/@ownedEnd.0 #/1/@ownedElements.6/@ownedEnd.0">
        <attributes name="capacity" type="#/1/@ownedElements.22" lower="1" upper="1"/>
        <attributes name="maximalLimit" type="#/1/@ownedElements.22" lower="1" upper="1"/>
        <attributes name="maximalNormal" type="#/1/@ownedElements.22" lower="1" upper="1"/>
        <attributes name="maximumDecrease" type="#/1/@ownedElements.22" lower="1"
            upper="1"/>
        <attributes name="maximumIncrease" type="#/1/@ownedElements.22" lower="1"
            upper="1"/>
        <attributes name="minimalLimit" type="#/1/@ownedElements.22" lower="1" upper="1"/>
        <attributes name="minimalNormal" type="#/1/@ownedElements.22" lower="1" upper="1"/>
        <attributes name="valveOpen" type="#/1/@ownedElements.12" lower="1" upper="1"/>
        <constraints name="ValveOpenInv">
          <specification xsi:type="sTM:OpaqueExpression">
            <body>((self.valveOpen = ValveState::open) implies (self.program.mode = Mode::Initialization))</body>
          </specification>
        </constraints>
      </snapshotObjects>
      <snapshotObjects name="SteamMeasurementDevice" typedElement="#/1/@ownedElements.16/@context #/1/@ownedElements.11/@ownedEnd.1 #/1/@ownedElements.9/@ownedEnd.1">
        <attributes name="evaporationRate" type="#/1/@ownedElements.22" lower="1"
            upper="1"/>
      </snapshotObjects>
      <snapshotObjects name="Pump" typedElement="#/1/@ownedElements.7/@ownedEnd.1 #/1/@ownedElements.5/@ownedEnd.1 #/1/@ownedElements.6/@ownedEnd.1">
        <attributes name="capacity" type="#/1/@ownedElements.22" lower="1" upper="1"/>
        <attributes name="mode" type="#/1/@ownedElements.14" lower="1" upper="1"/>
      </snapshotObjects>
      <snapshotObjects name="PhysicalUnit">
        <attributes name="ready" type="#/1/@ownedElements.23" lower="1" upper="1"/>
      </snapshotObjects>
    </ownedElements>
    <ownedElements xsi:type="sTM:SnapshotClassifier" name="FirstSnapshot" isFirst="true">
      <generalization general="#/1/@ownedElements.0"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:SnapshotClassifier" name="LastSnapshot" isLast="true">
      <generalization general="#/1/@ownedElements.0"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="SteamBoilerControlProgram" memberEnd="#/1/@ownedElements.3/@ownedEnd.0 #/1/@ownedElements.3/@ownedEnd.1">
      <ownedEnd name="sb" type="#/1/@ownedElements.0/@snapshotObjects.3" association="#/1/@ownedElements.3"
          lower="1" upper="1"/>
      <ownedEnd name="program" type="#/1/@ownedElements.0/@snapshotObjects.1" association="#/1/@ownedElements.3"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="ControlProgramWLMD" memberEnd="#/1/@ownedElements.4/@ownedEnd.0 #/1/@ownedElements.4/@ownedEnd.1">
      <ownedEnd name="program" type="#/1/@ownedElements.0/@snapshotObjects.1" association="#/1/@ownedElements.4"
          lower="1" upper="1"/>
      <ownedEnd name="wlmd" type="#/1/@ownedElements.0/@snapshotObjects.0" association="#/1/@ownedElements.4"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="PumpControllerPump" memberEnd="#/1/@ownedElements.5/@ownedEnd.0 #/1/@ownedElements.5/@ownedEnd.1">
      <ownedEnd name="controller" type="#/1/@ownedElements.0/@snapshotObjects.2" association="#/1/@ownedElements.5"
          lower="1" upper="1"/>
      <ownedEnd name="pump" type="#/1/@ownedElements.0/@snapshotObjects.5" association="#/1/@ownedElements.5"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="SteamBoilerPump" memberEnd="#/1/@ownedElements.6/@ownedEnd.0 #/1/@ownedElements.6/@ownedEnd.1">
      <ownedEnd name="sb" type="#/1/@ownedElements.0/@snapshotObjects.3" association="#/1/@ownedElements.6"
          lower="1" upper="1"/>
      <ownedEnd name="pump" type="#/1/@ownedElements.0/@snapshotObjects.5" association="#/1/@ownedElements.6"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="ControlProgramPump" memberEnd="#/1/@ownedElements.7/@ownedEnd.0 #/1/@ownedElements.7/@ownedEnd.1">
      <ownedEnd name="program" type="#/1/@ownedElements.0/@snapshotObjects.1" association="#/1/@ownedElements.7"
          lower="1" upper="1"/>
      <ownedEnd name="pump" type="#/1/@ownedElements.0/@snapshotObjects.5" association="#/1/@ownedElements.7"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="ControlProgramPumpControler" memberEnd="#/1/@ownedElements.8/@ownedEnd.0 #/1/@ownedElements.8/@ownedEnd.1">
      <ownedEnd name="program" type="#/1/@ownedElements.0/@snapshotObjects.1" association="#/1/@ownedElements.8"
          lower="1" upper="1"/>
      <ownedEnd name="PC" type="#/1/@ownedElements.0/@snapshotObjects.2" association="#/1/@ownedElements.8"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="ControlProgramSMD" memberEnd="#/1/@ownedElements.9/@ownedEnd.0 #/1/@ownedElements.9/@ownedEnd.1">
      <ownedEnd name="program" type="#/1/@ownedElements.0/@snapshotObjects.1" association="#/1/@ownedElements.9"
          lower="1" upper="1"/>
      <ownedEnd name="smd" type="#/1/@ownedElements.0/@snapshotObjects.4" association="#/1/@ownedElements.9"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="SteamBoilerWLMD" memberEnd="#/1/@ownedElements.10/@ownedEnd.0 #/1/@ownedElements.10/@ownedEnd.1">
      <ownedEnd name="sb" type="#/1/@ownedElements.0/@snapshotObjects.3" association="#/1/@ownedElements.10"
          lower="1" upper="1"/>
      <ownedEnd name="wlmd" type="#/1/@ownedElements.0/@snapshotObjects.0" association="#/1/@ownedElements.10"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Association" name="SteamBoilerSMD" memberEnd="#/1/@ownedElements.11/@ownedEnd.0 #/1/@ownedElements.11/@ownedEnd.1">
      <ownedEnd name="sb" type="#/1/@ownedElements.0/@snapshotObjects.3" association="#/1/@ownedElements.11"
          lower="1" upper="1"/>
      <ownedEnd name="smd" type="#/1/@ownedElements.0/@snapshotObjects.4" association="#/1/@ownedElements.11"
          lower="1" upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Enumeration" name="ValveState" typedElement="#/1/@ownedElements.0/@snapshotObjects.3/@attributes.7"
        enumerationLiteral="#/1/@ownedElements.12/@ownedLiteral.0 #/1/@ownedElements.12/@ownedLiteral.1">
      <ownedLiteral name="open" enumeration="#/1/@ownedElements.12"/>
      <ownedLiteral name="closed" enumeration="#/1/@ownedElements.12"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Enumeration" name="Mode" typedElement="#/1/@ownedElements.0/@snapshotObjects.1/@attributes.1"
        enumerationLiteral="#/1/@ownedElements.13/@ownedLiteral.0 #/1/@ownedElements.13/@ownedLiteral.1 #/1/@ownedElements.13/@ownedLiteral.2 #/1/@ownedElements.13/@ownedLiteral.3 #/1/@ownedElements.13/@ownedLiteral.4">
      <ownedLiteral name="Normal" enumeration="#/1/@ownedElements.13"/>
      <ownedLiteral name="Initialization" enumeration="#/1/@ownedElements.13"/>
      <ownedLiteral name="Degraded" enumeration="#/1/@ownedElements.13"/>
      <ownedLiteral name="Rescue" enumeration="#/1/@ownedElements.13"/>
      <ownedLiteral name="EmergencyStop" enumeration="#/1/@ownedElements.13"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:Enumeration" name="State" typedElement="#/1/@ownedElements.0/@snapshotObjects.5/@attributes.1"
        enumerationLiteral="#/1/@ownedElements.14/@ownedLiteral.0 #/1/@ownedElements.14/@ownedLiteral.1">
      <ownedLiteral name="on" enumeration="#/1/@ownedElements.14"/>
      <ownedLiteral name="off" enumeration="#/1/@ownedElements.14"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:TransitionClass" name="Transition" isAbstract="true"
        isParentClass="true" transitionSubClasses="#/1/@ownedElements.16 #/1/@ownedElements.17 #/1/@ownedElements.18 #/1/@ownedElements.19 #/1/@ownedElements.20 #/1/@ownedElements.21"/>
    <ownedElements xsi:type="sTM:TransitionClass" name="SteamMeasurementDevice_getSteam"
        transitionParent="#/1/@ownedElements.15">
      <generalization general="#/1/@ownedElements.15"/>
      <attributes name="result" type="#/1/@ownedElements.22" upper="1"/>
      <constraints name="pre1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.transitionContext.program.mode = Mode::Normal)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <constraints name="post1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.evaporationRate = result)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <context name="transitionContext" type="#/1/@ownedElements.0/@snapshotObjects.4"
          upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:TransitionClass" name="ControlProgram_startOperation"
        transitionParent="#/1/@ownedElements.15">
      <generalization general="#/1/@ownedElements.15"/>
      <constraints name="pre1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.transitionContext.ready = false)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <constraints name="post1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.ready = true)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <context name="transitionContext" type="#/1/@ownedElements.0/@snapshotObjects.1"
          upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:TransitionClass" name="WaterLevelMeasurementDevice_getLevel"
        transitionParent="#/1/@ownedElements.15">
      <generalization general="#/1/@ownedElements.15"/>
      <attributes name="result" type="#/1/@ownedElements.22" upper="1"/>
      <constraints name="pre1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.transitionContext.program.mode = Mode::Normal)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <constraints name="post1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.waterLevel = result)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <context name="transitionContext" type="#/1/@ownedElements.0/@snapshotObjects.0"
          upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:TransitionClass" name="PumpController_closePump"
        transitionParent="#/1/@ownedElements.15">
      <generalization general="#/1/@ownedElements.15"/>
      <constraints name="pre1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.transitionContext.pump.mode = State::on)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <constraints name="post1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.pump.mode = State::off)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <context name="transitionContext" type="#/1/@ownedElements.0/@snapshotObjects.2"
          upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:TransitionClass" name="PumpController_openPump" transitionParent="#/1/@ownedElements.15">
      <generalization general="#/1/@ownedElements.15"/>
      <constraints name="pre1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.transitionContext.pump.mode = State::off)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <constraints name="post1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.pump.mode = State::on)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <context name="transitionContext" type="#/1/@ownedElements.0/@snapshotObjects.2"
          upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:TransitionClass" name="SteamBoiler_openValve" transitionParent="#/1/@ownedElements.15">
      <generalization general="#/1/@ownedElements.15"/>
      <constraints name="pre1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.transitionContext.valveOpen = ValveState::closed)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <constraints name="post1">
        <specification xsi:type="sTM:OpaqueExpression">
          <body>(self.valveOpen = ValveState::open)</body>
          <language>OCL</language>
        </specification>
      </constraints>
      <context name="transitionContext" type="#/1/@ownedElements.0/@snapshotObjects.3"
          upper="1"/>
    </ownedElements>
    <ownedElements xsi:type="sTM:DataType" name="Real" typedElement="#/1/@ownedElements.0/@snapshotObjects.4/@attributes.0 #/1/@ownedElements.16/@attributes.0 #/1/@ownedElements.0/@snapshotObjects.5/@attributes.0 #/1/@ownedElements.0/@snapshotObjects.0/@attributes.0 #/1/@ownedElements.18/@attributes.0 #/1/@ownedElements.0/@snapshotObjects.3/@attributes.0 #/1/@ownedElements.0/@snapshotObjects.3/@attributes.1 #/1/@ownedElements.0/@snapshotObjects.3/@attributes.2 #/1/@ownedElements.0/@snapshotObjects.3/@attributes.3 #/1/@ownedElements.0/@snapshotObjects.3/@attributes.4 #/1/@ownedElements.0/@snapshotObjects.3/@attributes.5 #/1/@ownedElements.0/@snapshotObjects.3/@attributes.6"/>
    <ownedElements xsi:type="sTM:DataType" name="Boolean" typedElement="#/1/@ownedElements.0/@snapshotObjects.6/@attributes.0 #/1/@ownedElements.0/@snapshotObjects.1/@attributes.0 #/1/@ownedElements.0/@snapshotObjects.1/@attributes.2 #/1/@ownedElements.0/@snapshotObjects.1/@attributes.3 #/1/@ownedElements.0/@snapshotObjects.1/@attributes.4 #/1/@ownedElements.0/@snapshotObjects.1/@attributes.5 #/1/@ownedElements.0/@snapshotObjects.1/@attributes.6 #/1/@ownedElements.0/@snapshotObjects.2/@attributes.0"/>
  </sTM:Model>
</xmi:XMI>
