[default]
Integer_min = -100
Integer_max = 100

String_max = 10

Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

# --- FirstSnapshot
FirstSnapshot_min = 1
FirstSnapshot_max = 1
FirstSnapshot = Set{s1}

# --- LastSnapshot
LastSnapshot_min = 1
LastSnapshot_max = 1
LastSnapshot = Set{s2,s3}

# --- Snapshot
Snapshot_min = 0
Snapshot_max = 2
Snapshot = Set{s2,s3}

# beforeTransition (beforeS:Snapshot, nextT:Transition)
beforeTransition_min = 1
beforeTransition_max = 3

# afterTransition (nextS:Snapshot, beforeT:Transition)
afterTransition_min = 1
afterTransition_max = 3

# --- ControlProgram
ControlProgram_min = 0
ControlProgram_max = 4

# --- ControlProgram_startOperation
ControlProgram_startOperation_min = 0
ControlProgram_startOperation_max = 3

# --- PhysicalUnit
PhysicalUnit_min = 0
PhysicalUnit_max = 4

# --- Pump
Pump_min = 0
Pump_max = 4

# --- PumpController
PumpController_min = 0
PumpController_max = 4

# --- PumpController_closePump
PumpController_closePump_min = 0
PumpController_closePump_max = 3

# --- PumpController_openPump
PumpController_openPump_min = 0
PumpController_openPump_max = 3

# --- Snapshot
Snapshot_min = 0
Snapshot_max = 2

# --- SteamBoiler
SteamBoiler_min = 0
SteamBoiler_max = 4

# --- SteamBoiler_openValve
SteamBoiler_openValve_min = 0
SteamBoiler_openValve_max = 3

# --- SteamMeasurementDevice
SteamMeasurementDevice_min = 0
SteamMeasurementDevice_max = 4

# --- SteamMeasurementDevice_getSteam
SteamMeasurementDevice_getSteam_min = 0
SteamMeasurementDevice_getSteam_max = 3

# --- WaterLevelMeasurementDevice
WaterLevelMeasurementDevice_min = 0
WaterLevelMeasurementDevice_max = 4

# --- WaterLevelMeasurementDevice_getLevel
WaterLevelMeasurementDevice_getLevel_min = 0
WaterLevelMeasurementDevice_getLevel_max = 3

# ControlProgramPump
ControlProgramPump_min = 0
ControlProgramPump_max = 4

# ControlProgramPumpControler
ControlProgramPumpControler_min = 0
ControlProgramPumpControler_max = 4

# ControlProgramSMD
ControlProgramSMD_min = 0
ControlProgramSMD_max = 4

# ControlProgramWLMD
ControlProgramWLMD_min = 0
ControlProgramWLMD_max = 4

# PumpControllerPump
PumpControllerPump_min = 0
PumpControllerPump_max = 4

# SnapshotControlProgram
SnapshotControlProgram_min = 0
SnapshotControlProgram_max = 4

# SnapshotPhysicalUnit
SnapshotPhysicalUnit_min = 0
SnapshotPhysicalUnit_max = 4

# SnapshotPump
SnapshotPump_min = 0
SnapshotPump_max = 4

# SnapshotPumpController
SnapshotPumpController_min = 0
SnapshotPumpController_max = 4

# SnapshotSteamBoiler
SnapshotSteamBoiler_min = 0
SnapshotSteamBoiler_max = 4

# SnapshotSteamMeasurementDevice
SnapshotSteamMeasurementDevice_min = 0
SnapshotSteamMeasurementDevice_max = 4

# SnapshotWaterLevelMeasurementDevice
SnapshotWaterLevelMeasurementDevice_min = 0
SnapshotWaterLevelMeasurementDevice_max = 4

# SteamBoilerControlProgram
SteamBoilerControlProgram_min = 0
SteamBoilerControlProgram_max = 4

# SteamBoilerPump
SteamBoilerPump_min = 0
SteamBoilerPump_max = 4

# SteamBoilerSMD
SteamBoilerSMD_min = 0
SteamBoilerSMD_max = 4

# SteamBoilerWLMD
SteamBoilerWLMD_min = 0
SteamBoilerWLMD_max = 4

# afterTransition
afterTransition_min = 0
afterTransition_max = 4

# beforeTransition
beforeTransition_min = 0
beforeTransition_max = 4

# ---
aggregationcyclefreeness = on
forbiddensharing = on