<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="acl" nsURI="https://vnu.edu.vn/sme/goal/acl/3.0" nsPrefix="acl">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="High-level ACL DSL metamodel. Entity, Role, and Association specialize Object. Group specializes Entity and composes Entity and Role declarations."/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AclModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonEmptyName UniqueObjectNames UniqueDataTypeNames"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG">
      <details key="NonEmptyName" value="name.size() > 0"/>
      <details key="UniqueObjectNames" value="Object.allInstances()->isUnique(name)"/>
      <details key="UniqueDataTypeNames" value="dataTypes->isUnique(name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//Object" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orgctx" upperBound="-1"
        eType="#//OrgCtx" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonEmptyName UniqueAttributeNames"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG">
      <details key="NonEmptyName" value="name.size() > 0"/>
      <details key="UniqueAttributeNames" value="attributes->isUnique(name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Object">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoSelfGeneralization AcyclicGeneralization"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG">
      <details key="NoSelfGeneralization" value="not generalization->includes(self)"/>
      <details key="AcyclicGeneralization" value="generalization->closure(e | e.generalization)->excludes(self)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrgCtx">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Group is both an Entity and a contained subsystem. It composes Entity declarations (including child Groups) and Role declarations."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orgctx" upperBound="-1"
        eType="#//OrgCtx" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//Object">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Role may point to parent Roles through roleGeneralization and to co-playable Roles through the symmetric compatibility relation. Ordinary Associations between Roles are also permitted; the two dedicated links retain their organizational semantics."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoSelfRoleGeneralization AcyclicRoleGeneralization NoSelfCompatibility SymmetricCompatibility"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG">
      <details key="NoSelfRoleGeneralization" value="not roleGeneralization->includes(self)"/>
      <details key="AcyclicRoleGeneralization" value="roleGeneralization->closure(r | r.roleGeneralization)->excludes(self)"/>
      <details key="NoSelfCompatibility" value="not compatibility->includes(self)"/>
      <details key="SymmetricCompatibility" value="compatibility->forAll(r | r.compatibility->includes(self))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleGeneralization" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compatibility" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Object">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An ACL association owns at least two AssociationEnds. Each end identifies its participating Object, optional role name, and lower/upper multiplicity bounds."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueEndRoles"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG">
      <details key="UniqueEndRoles" value="ends->select(e | not e.role.oclIsUndefined())->isUnique(role)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ends" lowerBound="2"
        upperBound="-1" eType="#//AssociationEnd" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationEnd">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="One navigable end of an Association. Its lower and upper attributes define the end multiplicity; upper = -1 denotes an unbounded limit."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonEmptyRole ValidMultiplicity"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG">
      <details key="NonEmptyRole" value="role.oclIsUndefined() or role.size() > 0"/>
      <details key="ValidMultiplicity" value="lower >= 0 and (upper = -1 or upper >= lower) and not (lower = 0 and upper = 0)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
        eType="#//Object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonEmptyName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG">
      <details key="NonEmptyName" value="name.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mutable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonEmptyName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/LPG">
      <details key="NonEmptyName" value="name.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
