package org.vnu.sme.goal.feature.conformance;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.prefs.Preferences;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

import org.tzi.use.gui.main.MainWindow;
import org.tzi.use.main.Session;
import org.vnu.sme.goal.dsl.bpmn.view.BpmnView;
import org.vnu.sme.goal.dsl.bpmnscenario.mm.BpmnScenarioSnapshot;
import org.vnu.sme.goal.dsl.bpmnscenario.mm.NodeOccurrence;
import org.vnu.sme.goal.verify.conformance.VisualConformanceSession;
import org.vnu.sme.goal.verify.conformance.VisualConformanceSession.Frame;
import org.vnu.sme.goal.verify.conformance.ScenarioTraceExplorer;
import org.vnu.sme.goal.verify.conformance.semantics.GoalTaskStatus;
import org.vnu.sme.goal.verify.conformance.semantics.IStarMarking;
import org.vnu.sme.goal.verify.conformance.semantics.QualityStatus;
import org.vnu.sme.goal.dsl.istar.mm.Goal;
import org.vnu.sme.goal.dsl.istar.mm.IntentionalElement;
import org.vnu.sme.goal.dsl.istar.mm.Obstacle;
import org.vnu.sme.goal.dsl.istar.mm.Quality;
import org.vnu.sme.goal.dsl.istar.mm.Resource;
import org.vnu.sme.goal.dsl.istar.mm.Task;
import org.vnu.sme.goal.dsl.istar.view.IStarView;
import org.vnu.sme.goal.dsl.istar.view.NodeBadge;
import org.vnu.sme.goal.trace.usetrace.IStarUseTraceEvaluator;

/** Synchronized BPMN-token and i*-satisfaction view for one input SOIL scenario. */
@SuppressWarnings("serial")
public final class StepConformanceForm extends JDialog {
    private static final Preferences PREFS = Preferences.userNodeForPackage(ConformanceForm.class);
    private static final Color C_OK = new Color(0, 120, 0);
    private static final Color C_ERR = new Color(160, 0, 0);
    private static final Color C_FULFILLED = new Color(30, 150, 60);
    private static final Color C_PENDING = new Color(180, 130, 0);
    private static final Color C_FALSE = new Color(170, 30, 30);
    private static final Color C_UNKNOWN = new Color(150, 150, 150);

    @SuppressWarnings("unused") private final Session useSession;
    private JTextField istarField, bpmnField, aclField, soilField;
    private IStarView istarView;
    private BpmnView bpmnView;
    private JLabel phaseLabel, detailLabel, statusLabel;
    private JButton previousButton, nextButton;
    private JComboBox<String> traceBox;
    private List<ScenarioTraceExplorer.Trace> exploredTraces = List.of();
    private boolean changingTraceBox;
    private VisualConformanceSession execution;
    private int displayedFrame = -1;

    public StepConformanceForm(Session session, MainWindow mainWindow) {
        super(mainWindow, "Scenario-driven visual conformance", false);
        this.useSession = session;
        buildUI();
        istarField.setText(PREFS.get("conformance4.istarFile", ""));
        bpmnField.setText(PREFS.get("conformance4.bpmn2File", ""));
        aclField.setText(PREFS.get("conformance4.aclFile", ""));
        soilField.setText(PREFS.get("conformance4.soilFile", ""));
        setSize(1500, 900);
        setLocationRelativeTo(mainWindow);
    }

    private void buildUI() {
        JPanel root = new JPanel(new BorderLayout(6, 6));
        root.setBorder(new EmptyBorder(8, 8, 8, 8));
        root.add(buildInputs(), BorderLayout.NORTH);
        istarView = new IStarView();
        bpmnView = new BpmnView();
        JSplitPane diagrams = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,
                titled("i* satisfaction for this scenario", istarView),
                titled("BPMN trace generated by the engine", bpmnView));
        diagrams.setResizeWeight(0.5);
        diagrams.setDividerLocation(740);
        root.add(diagrams, BorderLayout.CENTER);
        root.add(buildNavigation(), BorderLayout.SOUTH);
        setContentPane(root);
    }

    private JPanel buildInputs() {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        istarField = new JTextField(52); bpmnField = new JTextField(52);
        aclField = new JTextField(52); soilField = new JTextField(52);
        panel.add(fileRow("i* goals (.istar):", istarField, "istar"));
        panel.add(fileRow("BPMN2 process (.bpmn2):", bpmnField, "bpmn2"));
        panel.add(fileRow("ACL structure (.acl):", aclField, "acl"));
        panel.add(fileRow("Input scenario (.soil):", soilField, "soil"));
        JPanel row = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        JButton initialize = new JButton("Load and validate scenario");
        initialize.setFont(initialize.getFont().deriveFont(Font.BOLD));
        initialize.addActionListener(e -> initialize());
        row.add(initialize);
        JButton explore = new JButton("Explore all traces");
        explore.addActionListener(e -> explore());
        row.add(explore);
        traceBox = new JComboBox<>();
        traceBox.setPreferredSize(new Dimension(260, traceBox.getPreferredSize().height));
        traceBox.setEnabled(false);
        traceBox.addActionListener(e -> selectExploredTrace());
        row.add(traceBox);
        panel.add(row);
        return panel;
    }

    private JPanel fileRow(String label, JTextField field, String extension) {
        JPanel row = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 2));
        JLabel l = new JLabel(label);
        l.setPreferredSize(new Dimension(175, l.getPreferredSize().height));
        JButton browse = new JButton("Browse...");
        browse.addActionListener(e -> choose(field, extension));
        row.add(l); row.add(field); row.add(browse);
        return row;
    }

    private JPanel buildNavigation() {
        JPanel outer = new JPanel(new BorderLayout(0, 3));
        JPanel nav = new JPanel();
        previousButton = new JButton("Previous state");
        nextButton = new JButton("Execute next Activity");
        phaseLabel = new JLabel("No scenario loaded");
        previousButton.addActionListener(e -> show(displayedFrame - 1));
        nextButton.addActionListener(e -> next());
        nav.add(previousButton); nav.add(phaseLabel); nav.add(nextButton);
        detailLabel = new JLabel(" ");
        detailLabel.setFont(detailLabel.getFont().deriveFont(Font.BOLD));
        statusLabel = new JLabel(" ");
        outer.add(nav, BorderLayout.NORTH);
        outer.add(detailLabel, BorderLayout.CENTER);
        outer.add(statusLabel, BorderLayout.SOUTH);
        updateButtons();
        return outer;
    }

    private static JPanel titled(String title, JPanel content) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(new TitledBorder(new EtchedBorder(), title));
        panel.add(content, BorderLayout.CENTER);
        return panel;
    }

    private void initialize() {
        initialize(List.of());
    }

    private void initialize(List<Integer> choices) {
        execution = null;
        displayedFrame = -1;
        updateButtons();
        try {
            execution = VisualConformanceSession.prepare(
                    Path.of(istarField.getText().trim()), Path.of(bpmnField.getText().trim()),
                    Path.of(aclField.getText().trim()), Path.of(soilField.getText().trim()), choices);
            bpmnView.setModel(execution.bpmnModel());
            rememberInputs();
            show(0);
            status("INITIALIZATION PASS — role assignment, multiplicities and ACL constraints are valid.", C_OK);
        } catch (Exception ex) {
            phaseLabel.setText("INITIALIZATION FAILED");
            detailLabel.setText(html(ex.getMessage()));
            status("BPMN execution is blocked because the input scenario is invalid.", C_ERR);
        }
    }

    private void explore() {
        try {
            var assessment = ScenarioTraceExplorer.explore(
                    Path.of(istarField.getText().trim()), Path.of(bpmnField.getText().trim()),
                    Path.of(aclField.getText().trim()), Path.of(soilField.getText().trim()), 128);
            exploredTraces = assessment.traces();
            changingTraceBox = true;
            traceBox.removeAllItems();
            for (int i = 0; i < exploredTraces.size(); i++) {
                var trace = exploredTraces.get(i);
                traceBox.addItem("Trace " + (i + 1) + " — "
                        + (trace.rootsSatisfied() ? "goals fulfilled" : "goals not fulfilled"));
            }
            traceBox.setEnabled(!exploredTraces.isEmpty());
            changingTraceBox = false;
            status("Explored " + exploredTraces.size() + " trace(s): " + assessment.verdict()
                    + " [weak=" + assessment.weak() + ", strong=" + assessment.strong()
                    + ", stable=" + assessment.stable() + "]",
                    assessment.strong() ? C_OK : C_ERR);
            if (!exploredTraces.isEmpty()) initialize(exploredTraces.get(0).choices());
        } catch (Exception ex) {
            status("Trace exploration failed: " + ex.getMessage(), C_ERR);
        }
    }

    private void selectExploredTrace() {
        if (changingTraceBox) return;
        int index = traceBox.getSelectedIndex();
        if (index >= 0 && index < exploredTraces.size()) initialize(exploredTraces.get(index).choices());
    }

    private void next() {
        if (execution == null) return;
        try {
            // When reviewing history, Next first walks back to the latest generated frame.
            if (displayedFrame + 1 < execution.frames().size()) show(displayedFrame + 1);
            else {
                execution.next();
                show(execution.frames().size() - 1);
            }
            if (execution.ended()) {
                List<String> failures = execution.rootGoalFailures();
                status(failures.isEmpty()
                        ? "CONFORMANT — EndEvent reached and every i* root goal is fulfilled."
                        : "NOT CONFORMANT — EndEvent reached but root goals remain unsatisfied: "
                                + String.join(", ", failures), failures.isEmpty() ? C_OK : C_ERR);
            }
        } catch (Exception ex) {
            status("EXECUTION FAILED at the next BPMN step: " + ex.getMessage(), C_ERR);
            detailLabel.setText(html(ex.getMessage()));
        }
    }

    private void show(int index) {
        if (execution == null || index < 0 || index >= execution.frames().size()) return;
        displayedFrame = index;
        Frame frame = execution.frames().get(index);
        updateIStar(frame);
        updateBpmn(frame);
        if (frame.initial()) {
            phaseLabel.setText("INITIALIZED — process has not executed an Activity");
            detailLabel.setText("The complete SOIL input passed the initialization gate. Press Execute next Activity.");
        } else {
            phaseLabel.setText("Trace step " + frame.number() + " — "
                    + frame.processId() + "." + frame.activity().id());
            String stateDelta = frame.stateDelta().isEmpty() ? "no state change"
                    : "state: " + String.join("; ", frame.stateDelta());
            String goalDelta = frame.goalDelta().isEmpty() ? "no goal change"
                    : "goals: " + String.join("; ", frame.goalDelta());
            detailLabel.setText(html(stateDelta + "\n" + goalDelta));
        }
        updateButtons();
    }

    private void updateIStar(Frame frame) {
        var inst = IStarUseTraceEvaluator.evaluate(execution.goalModel(), frame.checkpoint());
        if (displayedFrame == 0) {
            istarView.setModel(inst.instanceModel());
            istarView.setActorLabelOverrides(inst.actorLabels());
            istarView.setNodeLabelOverrides(inst.nodeLabels());
        }
        istarView.setNodeBadges(badges(inst.instanceModel().allElements(), inst.instanceMarking()));
    }

    private void updateBpmn(Frame frame) {
        Map<String, String> runs = new LinkedHashMap<>();
        execution.processIds().forEach(id -> runs.put(id + "Run", id));
        List<NodeOccurrence> completed = frame.bpmnSnapshots().entrySet().stream()
                .flatMap(entry -> entry.getValue().completed().stream()
                        .filter(id -> frame.activity() == null || !entry.getKey().equals(frame.processId())
                                || !id.equals(frame.activity().id()))
                        .map(id -> occurrence(entry.getKey() + "Run", id))).toList();
        List<NodeOccurrence> active = frame.activity() == null ? List.of()
                : List.of(occurrence(frame.processId() + "Run", frame.activity().id()));
        bpmnView.setScenarioSnapshot(new BpmnScenarioSnapshot(
                runs, Map.of(), Map.of(), List.of(),
                completed, active, List.of(), List.of()));
    }

    private static NodeOccurrence occurrence(String run, String element) {
        return new NodeOccurrence(run, element, null, null);
    }

    private static Map<String, NodeBadge> badges(Map<String, IntentionalElement> elements, IStarMarking marking) {
        Map<String, NodeBadge> result = new LinkedHashMap<>();
        for (IntentionalElement element : elements.values()) {
            switch (element) {
                case Goal goal -> addGoalTask(result, goal.id(), marking.goalTaskStatus(goal.id()));
                case Task task -> addGoalTask(result, task.id(), marking.goalTaskStatus(task.id()));
                case Quality quality -> addQuality(result, quality.id(), marking.qualityStatus(quality.id()));
                case Resource ignored -> { }
                case Obstacle ignored -> { }
            }
        }
        return result;
    }

    private static void addGoalTask(Map<String, NodeBadge> badges, String id, GoalTaskStatus state) {
        badges.put(id, switch (state) {
            case FULFILLED -> new NodeBadge(C_FULFILLED, "F", "Fulfilled");
            case PENDING -> new NodeBadge(C_PENDING, "P", "Pending");
            case VIOLATED -> new NodeBadge(C_FALSE, "V", "Violated");
            case UNKNOWN -> new NodeBadge(C_UNKNOWN, "?", "Unknown / not reached");
        });
    }

    private static void addQuality(Map<String, NodeBadge> badges, String id, QualityStatus state) {
        badges.put(id, switch (state) {
            case TRUE -> new NodeBadge(C_FULFILLED, "T", "True");
            case FALSE -> new NodeBadge(C_FALSE, "F", "False");
            case UNKNOWN -> new NodeBadge(C_UNKNOWN, "?", "Unknown");
        });
    }

    private void choose(JTextField field, String extension) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("*." + extension, extension));
        if (!field.getText().isBlank()) chooser.setSelectedFile(new File(field.getText().trim()));
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            field.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }

    private void updateButtons() {
        int frameCount = execution == null ? 0 : execution.frames().size();
        previousButton.setEnabled(displayedFrame > 0);
        nextButton.setEnabled(execution != null &&
                (displayedFrame + 1 < frameCount || execution.canAdvance()));
    }

    private void rememberInputs() {
        PREFS.put("conformance4.istarFile", istarField.getText().trim());
        PREFS.put("conformance4.bpmn2File", bpmnField.getText().trim());
        PREFS.put("conformance4.aclFile", aclField.getText().trim());
        PREFS.put("conformance4.soilFile", soilField.getText().trim());
    }

    private void status(String message, Color color) {
        statusLabel.setText(message);
        statusLabel.setForeground(color);
    }

    private static String html(String message) {
        return "<html>" + String.valueOf(message).replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\n", "<br>") + "</html>";
    }
}
