package org.vnu.sme.goal.verify.aclstate;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

import org.vnu.sme.goal.dsl.acl.mm.AclModel;
import org.vnu.sme.goal.dsl.bpmn.mm.Activity;
import org.vnu.sme.goal.dsl.bpmn.mm.FlowElement;
import org.vnu.sme.goal.dsl.istar.mm.Actor;
import org.vnu.sme.goal.dsl.istar.mm.AndRefinement;
import org.vnu.sme.goal.dsl.istar.mm.Goal;
import org.vnu.sme.goal.dsl.istar.mm.GoalModel;
import org.vnu.sme.goal.dsl.istar.mm.GoalTaskElement;
import org.vnu.sme.goal.dsl.istar.mm.OrRefinement;
import org.vnu.sme.goal.dsl.istar.mm.Task;
import org.vnu.sme.goal.verify.aclstate.AclBpmnFlowRuntime.FlowStep;
import org.vnu.sme.goal.verify.aclstate.AclKodkodSymbolicModel.ObjectAtom;

import kodkod.ast.Formula;
import kodkod.engine.Solution;
import kodkod.engine.Solution.Outcome;
import kodkod.engine.Solver;
import kodkod.engine.satlab.SATFactory;

/** Whole BPMN bounded validation over object diagrams generated by Kodkod. */
public final class AclBpmnWholeProcessValidator {
    private static final int MAX_BPMN_CONFIGURATIONS = 50_000;
    private static final int MAX_BPMN_TRANSITIONS = 500_000;
    private static final int MAX_BOUNDED_EXECUTIONS = 20_000;
    private static final String BACKEND = "Kodkod / SAT4J";
    private static final Pattern OCL_IDENTIFIER = Pattern.compile("[A-Za-z_][A-Za-z0-9_]*");

    public enum Verdict { VALID, INVALID, INCONCLUSIVE }
    public enum ConsistencyVerdict {
        BPMN_ONLY, CONSISTENT, WEAKLY_CONSISTENT, INCONSISTENT, INCONCLUSIVE
    }

    public record MappingEntry(String processId, String activityId, String activityName,
                               String lane, String actor, String leafKind, String leafId,
                               int score, String basis) {}

    public record ProcessResult(String processId, String selfObject, Verdict verdict,
                                int productStates, int transitions, int completedStates,
                                int boundedExecutions, int loopCutoffs, int snapshotCutoffs,
                                int solverCalls, int realizableExecutions,
                                int goalAchievingExecutions,
                                List<String> counterexample,
                                List<String> witnessStates, String detail) {
        public ProcessResult {
            selfObject = selfObject == null ? "-" : selfObject;
            counterexample = List.copyOf(counterexample);
            witnessStates = List.copyOf(witnessStates);
        }
    }

    public record ValidationResult(Verdict verdict, ConsistencyVerdict consistency,
                                   String boundaryFile, int snapshots,
                                   int loopBound, String backend, int realizableExecutions,
                                   int goalAchievingExecutions, List<String> rootGoals,
                                   List<MappingEntry> mappings,
                                   List<ProcessResult> processes, String summary) {
        public ValidationResult {
            rootGoals = List.copyOf(rootGoals);
            mappings = List.copyOf(mappings);
            processes = List.copyOf(processes);
        }
    }

    private record RouteWork(Set<String> marking, List<FlowStep> route,
                             Map<String, Integer> cyclicExecutions) {}
    private record SolveResult(Verdict verdict, List<String> witness, String outcome) {}

    public ValidationResult validate(AclBpmnStateTraceEvaluator evaluator, AclModel acl,
                                     AclBpmnBoundary boundary) {
        return validate(evaluator, acl, boundary, null);
    }

    public ValidationResult validate(AclBpmnStateTraceEvaluator evaluator, AclModel acl,
                                     AclBpmnBoundary boundary, GoalModel goalModel) {
        List<ProcessResult> results = new ArrayList<>();
        for (AclBpmnFlowRuntime runtime : evaluator.runtimes()) {
            results.add(validateProcess(runtime, acl, boundary, goalModel));
        }
        Verdict verdict = results.stream().anyMatch(value -> value.verdict() == Verdict.INVALID)
                ? Verdict.INVALID
                : results.stream().anyMatch(value -> value.verdict() == Verdict.INCONCLUSIVE)
                        ? Verdict.INCONCLUSIVE : Verdict.VALID;
        int calls = results.stream().mapToInt(ProcessResult::solverCalls).sum();
        int executions = results.stream().mapToInt(ProcessResult::boundedExecutions).sum();
        int realizable = results.stream().mapToInt(ProcessResult::realizableExecutions).sum();
        int achieved = goalModel == null ? 0 : results.stream()
                .mapToInt(ProcessResult::goalAchievingExecutions).sum();
        ConsistencyVerdict consistency = goalModel == null ? ConsistencyVerdict.BPMN_ONLY
                : results.stream().anyMatch(value -> value.verdict() == Verdict.INCONCLUSIVE)
                        ? ConsistencyVerdict.INCONCLUSIVE
                        : achieved == 0 ? ConsistencyVerdict.INCONSISTENT
                        : achieved == realizable ? ConsistencyVerdict.CONSISTENT
                        : ConsistencyVerdict.WEAKLY_CONSISTENT;
        List<String> roots = goalModel == null ? List.of() : rootGoalLabels(goalModel);
        List<MappingEntry> mappings = goalModel == null ? List.of()
                : inferMappings(evaluator, goalModel);
        String summary = goalModel == null ? switch (verdict) {
            case VALID -> BACKEND + " generated ACL object diagrams and returned SAT for all "
                    + executions + " maximal bounded BPMN execution(s): loop-bound="
                    + boundary.loopBound() + ", snapshots=" + boundary.snapshots()
                    + " (" + calls + " solver call(s)).";
            case INVALID -> BACKEND + " returned UNSAT for at least one bounded BPMN execution,"
                    + " or found a structural BPMN deadlock.";
            case INCONCLUSIVE -> "Whole validation is inconclusive because the symbolic OCL fragment"
                    + " or an exploration safety limit was exceeded.";
        } : switch (consistency) {
            case CONSISTENT -> "CONSISTENT: every one of " + realizable
                    + " bounded BPMN execution(s) has a generated ACL state path that fulfills all root iStar goals.";
            case WEAKLY_CONSISTENT -> "WEAKLY_CONSISTENT: " + achieved + " of " + realizable
                    + " bounded BPMN execution(s) can fulfill all root iStar goals.";
            case INCONSISTENT -> "INCONSISTENT: no bounded BPMN execution can fulfill all root iStar goals.";
            case INCONCLUSIVE -> "Integrated ACL + BPMN + iStar validation is inconclusive because a symbolic"
                    + " expression or exploration safety limit could not be decided.";
            case BPMN_ONLY -> throw new IllegalStateException();
        };
        Verdict integratedVerdict = goalModel == null ? verdict : switch (consistency) {
            case CONSISTENT -> Verdict.VALID;
            case WEAKLY_CONSISTENT, INCONCLUSIVE -> Verdict.INCONCLUSIVE;
            case INCONSISTENT -> Verdict.INVALID;
            case BPMN_ONLY -> verdict;
        };
        return new ValidationResult(integratedVerdict, consistency, boundary.file().toString(),
                boundary.snapshots(), boundary.loopBound(), BACKEND, realizable, achieved,
                roots, mappings, results, summary);
    }

    private ProcessResult validateProcess(AclBpmnFlowRuntime runtime, AclModel acl,
                                          AclBpmnBoundary boundary, GoalModel goalModel) {
        if (runtime.process().groupClass() == null) {
            return result(runtime, null, Verdict.INCONCLUSIVE, 0, 0, 0, 0, 0, 0, 0,
                    List.of(), List.of(), "Whole symbolic validation requires pool ... for <GroupClass>.");
        }

        final AclKodkodSymbolicModel symbolic;
        try {
            symbolic = new AclKodkodSymbolicModel(acl, boundary);
        } catch (RuntimeException error) {
            return result(runtime, null, Verdict.INCONCLUSIVE, 0, 0, 0, 0, 0, 0, 0,
                    List.of(), List.of(), message(error));
        }
        final AclIStarSymbolicSemantics goals;
        try {
            goals = goalModel == null ? null : new AclIStarSymbolicSemantics(symbolic, goalModel);
        } catch (RuntimeException error) {
            return result(runtime, null, Verdict.INCONCLUSIVE, 0, 0, 0, 0, 0, 0, 0,
                    List.of(), List.of(), message(error));
        }
        List<ObjectAtom> selfCandidates = symbolic.processSelfCandidates(runtime.process().groupClass());
        AclBpmnBoundary.Scope selfScope = boundary.objectScopes().get(runtime.process().groupClass());
        if (selfCandidates.isEmpty() || selfScope == null || selfScope.lower() < 1) {
            return result(runtime, null, Verdict.INCONCLUSIVE, 0, 0, 0, 0, 0, 0, 0,
                    List.of(), List.of(), "Boundary must require at least one "
                            + runtime.process().groupClass() + " object for process self.");
        }
        // Potential object atoms of one classifier are symmetric. Fixing the first mandatory
        // representative breaks symmetry without losing a process-instance behavior.
        ObjectAtom self = selfCandidates.get(0);
        String preflight = preflight(symbolic, self);
        if (preflight != null) {
            return result(runtime, self.id(), Verdict.INCONCLUSIVE, 0, 0, 0, 0, 0, 0, 1,
                    List.of(), List.of(), preflight);
        }
        Set<String> cyclicFlows = cyclicFlows(runtime);
        Deque<RouteWork> stack = new ArrayDeque<>();
        stack.push(new RouteWork(runtime.initialMarking(), List.of(), Map.of()));

        int configurations = 0;
        int transitions = 0;
        int executions = 0;
        int completed = 0;
        int loopCutoffs = 0;
        int snapshotCutoffs = 0;
        int solverCalls = 1;
        int realizableExecutions = 0;
        int goalAchievingExecutions = 0;
        List<String> exampleWitness = List.of();
        List<String> goalCounterexample = List.of();

        while (!stack.isEmpty()) {
            if (configurations >= MAX_BPMN_CONFIGURATIONS
                    || transitions >= MAX_BPMN_TRANSITIONS
                    || executions >= MAX_BOUNDED_EXECUTIONS) {
                return result(runtime, self.id(), Verdict.INCONCLUSIVE, configurations, transitions,
                        completed, executions, loopCutoffs, snapshotCutoffs, solverCalls,
                        routeLabels(stack.peek().route()), exampleWitness,
                        "Bounded BPMN route enumeration exceeded its safety limit.");
            }

            RouteWork current = stack.pop();
            configurations++;
            boolean complete = runtime.fullyConsumed(current.marking());
            boolean snapshotLimit = current.route().size() + 1 >= boundary.snapshots();
            if (complete || snapshotLimit) {
                executions++;
                if (complete) completed++;
                else snapshotCutoffs++;
                SolveResult solved = solve(symbolic, runtime, current.route(), self);
                solverCalls++;
                if (solved.verdict() != Verdict.VALID) {
                    if (solved.verdict() == Verdict.INCONCLUSIVE || goals == null) {
                        return failed(runtime, self, solved, configurations, transitions, completed,
                                executions, loopCutoffs, snapshotCutoffs, solverCalls,
                                realizableExecutions, goalAchievingExecutions, current.route());
                    }
                    continue;
                }
                realizableExecutions++;
                if (goals == null) {
                    if (exampleWitness.isEmpty()) exampleWitness = solved.witness();
                } else {
                    SolveResult achieved = solve(symbolic, runtime, current.route(), self,
                            goals.rootGoalsSatisfied(current.route().size() + 1));
                    solverCalls++;
                    if (achieved.verdict() == Verdict.INCONCLUSIVE) {
                        return failed(runtime, self, achieved, configurations, transitions, completed,
                                executions, loopCutoffs, snapshotCutoffs, solverCalls,
                                realizableExecutions, goalAchievingExecutions, current.route());
                    }
                    if (achieved.verdict() == Verdict.VALID) {
                        goalAchievingExecutions++;
                        if (exampleWitness.isEmpty()) exampleWitness = achieved.witness();
                    } else if (goalCounterexample.isEmpty()) {
                        goalCounterexample = routeLabels(current.route());
                    }
                }
                continue;
            }

            List<FlowStep> enabled = runtime.enabledSteps(current.marking());
            if (enabled.isEmpty()) {
                if (goals != null) {
                    executions++;
                    SolveResult deadlock = solve(symbolic, runtime, current.route(), self);
                    solverCalls++;
                    if (deadlock.verdict() == Verdict.INCONCLUSIVE) {
                        return failed(runtime, self, deadlock, configurations, transitions, completed,
                                executions, loopCutoffs, snapshotCutoffs, solverCalls,
                                realizableExecutions, goalAchievingExecutions, current.route());
                    }
                    if (deadlock.verdict() == Verdict.VALID) {
                        realizableExecutions++;
                        if (goalCounterexample.isEmpty()) goalCounterexample = routeLabels(current.route());
                    }
                    continue;
                }
                return result(runtime, self.id(), Verdict.INVALID, configurations, transitions,
                        completed, executions, loopCutoffs, snapshotCutoffs, solverCalls,
                        routeLabels(current.route()), exampleWitness,
                        "Reachable BPMN flow state has no executable flow: " + sorted(current.marking()));
            }
            List<FlowStep> withinLoopBound = enabled.stream()
                    .filter(step -> !cyclicFlows.contains(step.flow().id())
                            || current.cyclicExecutions().getOrDefault(step.flow().id(), 0)
                                    < boundary.loopBound())
                    .toList();
            if (withinLoopBound.isEmpty()) {
                executions++;
                loopCutoffs++;
                SolveResult solved = solve(symbolic, runtime, current.route(), self);
                solverCalls++;
                if (solved.verdict() != Verdict.VALID) {
                    if (solved.verdict() == Verdict.INCONCLUSIVE || goals == null) {
                        return failed(runtime, self, solved, configurations, transitions, completed,
                                executions, loopCutoffs, snapshotCutoffs, solverCalls,
                                realizableExecutions, goalAchievingExecutions, current.route());
                    }
                    continue;
                }
                realizableExecutions++;
                if (goals == null) {
                    if (exampleWitness.isEmpty()) exampleWitness = solved.witness();
                } else {
                    SolveResult achieved = solve(symbolic, runtime, current.route(), self,
                            goals.rootGoalsSatisfied(current.route().size() + 1));
                    solverCalls++;
                    if (achieved.verdict() == Verdict.INCONCLUSIVE) {
                        return failed(runtime, self, achieved, configurations, transitions, completed,
                                executions, loopCutoffs, snapshotCutoffs, solverCalls,
                                realizableExecutions, goalAchievingExecutions, current.route());
                    }
                    if (achieved.verdict() == Verdict.VALID) {
                        goalAchievingExecutions++;
                        if (exampleWitness.isEmpty()) exampleWitness = achieved.witness();
                    } else if (goalCounterexample.isEmpty()) {
                        goalCounterexample = routeLabels(current.route());
                    }
                }
                continue;
            }

            for (int index = withinLoopBound.size() - 1; index >= 0; index--) {
                FlowStep step = withinLoopBound.get(index);
                transitions++;
                List<FlowStep> route = new ArrayList<>(current.route());
                route.add(step);
                Map<String, Integer> counts = new LinkedHashMap<>(current.cyclicExecutions());
                if (cyclicFlows.contains(step.flow().id())) counts.merge(step.flow().id(), 1, Integer::sum);
                stack.push(new RouteWork(runtime.execute(current.marking(), step),
                        List.copyOf(route), Map.copyOf(counts)));
            }
        }

        Verdict processVerdict = goals == null || goalAchievingExecutions > 0
                ? Verdict.VALID : Verdict.INVALID;
        String detail = goals == null
                ? BACKEND + " synthesized a formal ACL state path for every maximal bounded execution; "
                        + "no AOL scenario was loaded or used."
                : BACKEND + " found " + goalAchievingExecutions + " goal-achieving path(s) among "
                        + realizableExecutions + " realizable bounded BPMN execution(s). Root targets: "
                        + String.join(", ", goals.rootGoalLabels())
                        + ". iStar was evaluated over the generated ACL path, not an iStar state space.";
        return result(runtime, self.id(), processVerdict, configurations, transitions, completed,
                executions, loopCutoffs, snapshotCutoffs, solverCalls, realizableExecutions,
                goalAchievingExecutions, goalCounterexample, exampleWitness, detail);
    }

    private SolveResult solve(AclKodkodSymbolicModel symbolic, AclBpmnFlowRuntime runtime,
                              List<FlowStep> route, ObjectAtom self) {
        return solve(symbolic, runtime, route, self, null);
    }

    private SolveResult solve(AclKodkodSymbolicModel symbolic, AclBpmnFlowRuntime runtime,
                              List<FlowStep> route, ObjectAtom self, Formula extra) {
        try {
            Formula formula = symbolic.structuralFormula();
            for (int index = 0; index <= route.size(); index++) {
                formula = formula.and(symbolic.exists(symbolic.frame(index), self));
            }
            for (int index = 0; index < route.size(); index++) {
                FlowStep step = route.get(index);
                var before = symbolic.frame(index);
                var after = symbolic.frame(index + 1);
                for (String pre : runtime.preExpressions(step)) {
                    formula = formula.and(symbolic.expression(pre, before, before, self));
                }
                for (String post : runtime.postExpressions(step)) {
                    formula = formula.and(symbolic.expression(post, after, before, self));
                }
            }
            if (extra != null) formula = formula.and(extra);
            Solver solver = new Solver();
            solver.options().setSolver(SATFactory.DefaultSAT4J);
            solver.options().setBitwidth(10);
            Solution solution = solver.solve(formula, symbolic.bounds());
            boolean sat = solution.outcome() == Outcome.SATISFIABLE
                    || solution.outcome() == Outcome.TRIVIALLY_SATISFIABLE;
            return sat
                    ? new SolveResult(Verdict.VALID,
                            symbolic.decodePath(solution, route.size() + 1), solution.outcome().toString())
                    : new SolveResult(Verdict.INVALID, List.of(), solution.outcome().toString());
        } catch (IllegalArgumentException unsupported) {
            return new SolveResult(Verdict.INCONCLUSIVE, List.of(), message(unsupported));
        } catch (RuntimeException | LinkageError solverError) {
            return new SolveResult(Verdict.INCONCLUSIVE, List.of(),
                    "Kodkod solver error: " + message(solverError));
        }
    }

    private String preflight(AclKodkodSymbolicModel symbolic, ObjectAtom self) {
        try {
            Formula formula = symbolic.structuralFormula();
            for (int index = 0; index < symbolic.frameCount(); index++) {
                formula = formula.and(symbolic.exists(symbolic.frame(index), self));
            }
            Solver solver = new Solver();
            solver.options().setSolver(SATFactory.DefaultSAT4J);
            solver.options().setBitwidth(10);
            Solution solution = solver.solve(formula, symbolic.bounds());
            boolean sat = solution.outcome() == Outcome.SATISFIABLE
                    || solution.outcome() == Outcome.TRIVIALLY_SATISFIABLE;
            return sat ? null : "ACL invariants and boundary admit no symbolic system state ("
                    + solution.outcome() + "); BPMN was not judged.";
        } catch (RuntimeException | LinkageError error) {
            return "Cannot establish boundary consistency: " + message(error);
        }
    }

    private static ProcessResult failed(AclBpmnFlowRuntime runtime, ObjectAtom self,
                                        SolveResult solved, int configurations, int transitions,
                                        int completed, int executions, int loopCutoffs,
                                        int snapshotCutoffs, int solverCalls,
                                        int realizableExecutions, int goalAchievingExecutions,
                                        List<FlowStep> route) {
        String last = route.isEmpty() ? "initial state"
                : runtime.contractDescription(route.get(route.size() - 1));
        String meaning = solved.verdict() == Verdict.INVALID
                ? "no ACL object-diagram path exists inside the boundary"
                : "the symbolic encoder could not decide this bounded execution";
        return result(runtime, self.id(), solved.verdict(), configurations, transitions,
                completed, executions, loopCutoffs, snapshotCutoffs, solverCalls,
                realizableExecutions, goalAchievingExecutions, routeLabels(route), List.of(),
                BACKEND + " returned " + solved.outcome()
                        + ": " + meaning + ". Last contract: " + last);
    }

    private static ProcessResult result(AclBpmnFlowRuntime runtime, String self, Verdict verdict,
                                        int configurations, int transitions, int completed,
                                        int executions, int loopCutoffs, int snapshotCutoffs,
                                        int solverCalls, List<String> route,
                                        List<String> witness, String detail) {
        return result(runtime, self, verdict, configurations, transitions, completed, executions,
                loopCutoffs, snapshotCutoffs, solverCalls, 0, 0, route, witness, detail);
    }

    private static ProcessResult result(AclBpmnFlowRuntime runtime, String self, Verdict verdict,
                                        int configurations, int transitions, int completed,
                                        int executions, int loopCutoffs, int snapshotCutoffs,
                                        int solverCalls, int realizableExecutions,
                                        int goalAchievingExecutions, List<String> route,
                                        List<String> witness, String detail) {
        return new ProcessResult(runtime.process().id(), self, verdict, configurations,
                transitions, completed, executions, loopCutoffs, snapshotCutoffs,
                solverCalls, realizableExecutions, goalAchievingExecutions, route, witness, detail);
    }

    private static List<String> rootGoalLabels(GoalModel model) {
        Set<String> children = refinementChildren(model);
        return model.getActors().stream().flatMap(actor -> actor.elements().stream()
                .filter(Goal.class::isInstance).map(Goal.class::cast)
                .filter(goal -> !children.contains(goal.id()))
                .map(goal -> actor.name() + "." + goal.id())).toList();
    }

    /**
     * Produces an inspectable, inferred mapping. It is explanatory metadata;
     * consistency itself is proved from the OCL formulas, not from this score.
     */
    private static List<MappingEntry> inferMappings(AclBpmnStateTraceEvaluator evaluator,
                                                    GoalModel model) {
        Set<String> parents = new LinkedHashSet<>();
        Map<String, Actor> owners = new LinkedHashMap<>();
        List<GoalTaskElement> leaves = new ArrayList<>();
        for (Actor actor : model.getActors()) {
            actor.elements().stream().filter(GoalTaskElement.class::isInstance)
                    .map(GoalTaskElement.class::cast).forEach(element -> owners.put(element.id(), actor));
            actor.refinements().forEach(refinement -> parents.add(refinement.parent()));
        }
        owners.keySet().stream().filter(id -> !parents.contains(id))
                .map(model::findElement).flatMap(java.util.Optional::stream)
                .filter(GoalTaskElement.class::isInstance).map(GoalTaskElement.class::cast)
                .forEach(leaves::add);

        List<MappingEntry> result = new ArrayList<>();
        for (AclBpmnFlowRuntime runtime : evaluator.runtimes()) {
            for (FlowElement element : runtime.process().flowElements()) {
                if (!(element instanceof Activity activity)) continue;
                String lane = runtime.process().lanes().stream()
                        .filter(value -> value.flowElements().stream()
                                .anyMatch(item -> item.id().equals(activity.id())))
                        .map(value -> value.id()).findFirst().orElse("-");
                GoalTaskElement best = null;
                int bestScore = 0;
                String bestBasis = "no matching leaf contract";
                for (GoalTaskElement leaf : leaves) {
                    Actor actor = owners.get(leaf.id());
                    if (!lane.equals("-") && actor != null && !lane.equalsIgnoreCase(actor.name())) continue;
                    int name = nameScore(activity.id(), activity.name(), leaf.id());
                    int contract = contractScore(activity, leaf);
                    int score = Math.min(100, name + contract);
                    if (score > bestScore) {
                        best = leaf;
                        bestScore = score;
                        bestBasis = "identifier=" + name + ", shared OCL vocabulary=" + contract;
                    }
                }
                if (best == null || bestScore < 25) {
                    result.add(new MappingEntry(runtime.process().id(), activity.id(),
                            activity.name() == null ? activity.id() : activity.name(), lane,
                            "-", "-", "-", bestScore, "unmapped: " + bestBasis));
                } else {
                    Actor actor = owners.get(best.id());
                    result.add(new MappingEntry(runtime.process().id(), activity.id(),
                            activity.name() == null ? activity.id() : activity.name(), lane,
                            actor == null ? "-" : actor.name(),
                            best instanceof Goal ? "Goal" : "Task", best.id(), bestScore,
                            "inferred: " + bestBasis));
                }
            }
        }
        return List.copyOf(result);
    }

    private static int nameScore(String activityId, String activityName, String leafId) {
        Set<String> activity = words(activityId + " " + String.valueOf(activityName));
        Set<String> leaf = words(leafId);
        if (safe(activityId).equalsIgnoreCase(safe(leafId))) return 60;
        return (int) Math.round(60.0 * jaccard(activity, leaf));
    }

    private static int contractScore(Activity activity, GoalTaskElement leaf) {
        String activityOcl = activity.postconditions().stream()
                .map(value -> value.oclBody()).reduce("", (left, right) -> left + " " + right);
        String leafOcl = leaf instanceof Goal goal ? String.valueOf(goal.oclSource())
                : ((Task) leaf).postconditions().stream().map(value -> value.oclBody())
                        .reduce("", (left, right) -> left + " " + right);
        return (int) Math.round(40.0 * jaccard(oclWords(activityOcl), oclWords(leafOcl)));
    }

    private static Set<String> refinementChildren(GoalModel model) {
        Set<String> result = new LinkedHashSet<>();
        for (Actor actor : model.getActors()) {
            for (var refinement : actor.refinements()) {
                switch (refinement) {
                    case AndRefinement and -> result.addAll(and.children());
                    case OrRefinement or -> result.add(or.child());
                }
            }
        }
        return result;
    }

    private static Set<String> words(String source) {
        Set<String> result = new LinkedHashSet<>();
        for (String value : String.valueOf(source).replaceAll("([a-z0-9])([A-Z])", "$1 $2")
                .toLowerCase().split("[^a-z0-9]+")) {
            String stem = stem(value);
            if (stem.length() > 2 && !Set.of("the", "for", "and", "task", "activity").contains(stem)) {
                result.add(stem);
            }
        }
        return result;
    }

    private static Set<String> oclWords(String source) {
        Set<String> result = new LinkedHashSet<>();
        var matcher = OCL_IDENTIFIER.matcher(String.valueOf(source));
        while (matcher.find()) {
            String value = stem(matcher.group().toLowerCase());
            if (!Set.of("self", "group", "and", "or", "not", "true", "false", "forall",
                    "target", "source", "in", "classroom").contains(value)) result.add(value);
        }
        return result;
    }

    private static String stem(String value) {
        if (value.endsWith("ied") && value.length() > 5) return value.substring(0, value.length() - 3) + "y";
        if (value.endsWith("ing") && value.length() > 6) return value.substring(0, value.length() - 3);
        if (value.endsWith("ed") && value.length() > 5) return value.substring(0, value.length() - 2);
        if (value.endsWith("s") && value.length() > 4) return value.substring(0, value.length() - 1);
        return value;
    }

    private static double jaccard(Set<String> left, Set<String> right) {
        if (left.isEmpty() || right.isEmpty()) return 0;
        Set<String> intersection = new LinkedHashSet<>(left);
        intersection.retainAll(right);
        Set<String> union = new LinkedHashSet<>(left);
        union.addAll(right);
        return (double) intersection.size() / union.size();
    }

    private static String safe(String value) {
        return String.valueOf(value).replaceAll("[^A-Za-z0-9]", "");
    }

    private static Set<String> cyclicFlows(AclBpmnFlowRuntime runtime) {
        Map<String, Set<String>> graph = new LinkedHashMap<>();
        for (var flow : runtime.process().sequenceFlows()) {
            graph.computeIfAbsent(flow.source().id(), ignored -> new LinkedHashSet<>())
                    .add(flow.target().id());
        }
        Set<String> result = new LinkedHashSet<>();
        for (var flow : runtime.process().sequenceFlows()) {
            if (reachable(graph, flow.target().id(), flow.source().id())) {
                result.add(AclBpmnFlowRuntime.arcId(flow));
            }
        }
        return Set.copyOf(result);
    }

    private static boolean reachable(Map<String, Set<String>> graph, String start, String target) {
        Deque<String> pending = new ArrayDeque<>();
        Set<String> seen = new LinkedHashSet<>();
        pending.push(start);
        while (!pending.isEmpty()) {
            String node = pending.pop();
            if (node.equals(target)) return true;
            if (!seen.add(node)) continue;
            graph.getOrDefault(node, Set.of()).forEach(pending::push);
        }
        return false;
    }

    private static List<String> routeLabels(List<FlowStep> route) {
        return route.stream().map(FlowStep::label).toList();
    }

    private static List<String> sorted(Set<String> values) {
        return values.stream().sorted().toList();
    }

    private static String message(Throwable throwable) {
        return throwable.getMessage() == null || throwable.getMessage().isBlank()
                ? throwable.getClass().getSimpleName() : throwable.getMessage();
    }
}
