[default]
Integer_min = 0
Integer_max = 100
String_max = 10
Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# BankAccount
BankAccount_min = 1
BankAccount_max = 1
# DebitCard
DebitCard_min = 2
DebitCard_max = 2
# Snapshot
#Snapshot_min = 2
#Snapshot_max = 2
# Filmstrip
#Filmstrip_min = 1
#Filmstrip_max = 1

### Associations
# AccountCard
AccountCard_min = 2
AccountCard_max = 2
# SnapshotBankAccount
#SnapshotBankAccount_min = 2
#SnapshotBankAccount_max = 2
# SnapshotDebitCard
#SnapshotDebitCard_min = 1
#SnapshotDebitCard_max = 1
# PredSuccBankAccount
#PredSuccBankAccount_min = 1
#PredSuccBankAccount_max = 1
# PredSuccDebitCard
#PredSuccDebitCard_min = 0
#PredSuccDebitCard_max = 0

### Operation Call Classes
# assignNewCard_BankAccountOpC
#assignNewCard_BankAccountOpC_min = 1
#assignNewCard_BankAccountOpC_max = 1
# deposit_BankAccountOpC
#deposit_BankAccountOpC_min = 0
#deposit_BankAccountOpC_max = 0
# pay_DebitCardOpC
#pay_DebitCardOpC_min = 0
#pay_DebitCardOpC_max = 0
# withdraw_BankAccountOpC
#withdraw_BankAccountOpC_min = 0
#withdraw_BankAccountOpC_max = 0


aggregationcyclefreeness = on
forbiddensharing = on