[default]
Integer_min = -100
Integer_max = 100

String_max = 10

Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

# --- FirstSnapshot
FirstSnapshot_min = 1
FirstSnapshot_max = 1
FirstSnapshot = Set{s1}

# --- LastSnapshot
LastSnapshot_min = 1
LastSnapshot_max = 1
LastSnapshot = Set{s2,s3}

# --- Snapshot
Snapshot_min = 0
Snapshot_max = 2
Snapshot = Set{s2,s3}

# beforeTransition (beforeS:Snapshot, nextT:Transition)
beforeTransition_min = 1
beforeTransition_max = 3

# afterTransition (nextS:Snapshot, beforeT:Transition)
afterTransition_min = 1
afterTransition_max = 3

# --- BankAccount
BankAccount_min = 0
BankAccount_max = 12

# --- BankAccount_assignNewCard
BankAccount_assignNewCard_min = 0
BankAccount_assignNewCard_max = 3

# --- BankAccount_deposit
BankAccount_deposit_min = 0
BankAccount_deposit_max = 3

# --- BankAccount_withdraw
BankAccount_withdraw_min = 0
BankAccount_withdraw_max = 3

# --- DebitCard
DebitCard_min = 0
DebitCard_max = 12

# --- DebitCard_pay
DebitCard_pay_min = 0
DebitCard_pay_max = 3

# --- Snapshot
Snapshot_min = 0
Snapshot_max = 2

# AccountCard
AccountCard_min = 0
AccountCard_max = 12

# SnapshotBankAccount
SnapshotBankAccount_min = 0
SnapshotBankAccount_max = 12

# SnapshotDebitCard
SnapshotDebitCard_min = 0
SnapshotDebitCard_max = 12

# afterTransition
afterTransition_min = 0
afterTransition_max = 12

# beforeTransition
beforeTransition_min = 0
beforeTransition_max = 12

# ---
aggregationcyclefreeness = on
forbiddensharing = on