[default]
Integer_min = 0
Integer_max = 100
String_max = 10
Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 2
Snapshot_max = 2
# Filmstrip
Filmstrip_min = 1
Filmstrip_max = 1
# VendingMachine
VendingMachine_min = 2
VendingMachine_max = 2
# Item
Item_min = 2
Item_max = 2

### Operation Classes
# insertMoney_VendingMachineOpC
insertMoney_VendingMachineOpC_min = 1
insertMoney_VendingMachineOpC_max = 1
# selectItem_VendingMachineOpC
selectItem_VendingMachineOpC_min = 0
selectItem_VendingMachineOpC_max = 0
# dispenseItem_VendingMachineOpC
dispenseItem_VendingMachineOpC_min = 0
dispenseItem_VendingMachineOpC_max = 0

### Associations
# VendingMachineItem
VendingMachineItem_min = 2
VendingMachineItem_max = 2
# SnapshotItem
SnapshotItem_min = 2
SnapshotItem_max = 2
# SnapshotVendingMachine
SnapshotVendingMachine_min = 2
SnapshotVendingMachine_max = 2
# PredSuccVendingMachine
PredSuccVendingMachine_min = 1
PredSuccVendingMachine_max = 1
# PredSuccItem
PredSuccItem_min = 1
PredSuccItem_max = 1

aggregationcyclefreeness = on
forbiddensharing = on