[default]
Integer_min = 0
Integer_max = 100
String_max = 10
Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 3
Snapshot_max = 3
# Filmstrip
Filmstrip_min = 2
Filmstrip_max = 2
# VendingMachine
VendingMachine_min = 3
VendingMachine_max = 3
# Item
Item_min = 3
Item_max = 3

### Operation Classes
# insertMoney_VendingMachineOpC
insertMoney_VendingMachineOpC_min = 1
insertMoney_VendingMachineOpC_max = 1
# selectItem_VendingMachineOpC
selectItem_VendingMachineOpC_min = 1
selectItem_VendingMachineOpC_max = 1
# dispenseItem_VendingMachineOpC
dispenseItem_VendingMachineOpC_min = 0
dispenseItem_VendingMachineOpC_max = 0

### Associations
# VendingMachineItem
VendingMachineItem_min = 3
VendingMachineItem_max = 3
# SnapshotItem
SnapshotItem_min = 3
SnapshotItem_max = 3
# SnapshotVendingMachine
SnapshotVendingMachine_min = 3
SnapshotVendingMachine_max = 3
# PredSuccVendingMachine
PredSuccVendingMachine_min = 2
PredSuccVendingMachine_max = 2
# PredSuccItem
PredSuccItem_min = 2
PredSuccItem_max = 2

aggregationcyclefreeness = on
forbiddensharing = on