[default]
Integer_min = 0
Integer_max = 100
String_max = 10
Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 4
Snapshot_max = 4
# Filmstrip
Filmstrip_min = 3
Filmstrip_max = 3
# VendingMachine
VendingMachine_min = 4
VendingMachine_max = 4
# Item
Item_min = 4
Item_max = 4

### Operation Classes
# insertMoney_VendingMachineOpC
insertMoney_VendingMachineOpC_min = 1
insertMoney_VendingMachineOpC_max = 1
# selectItem_VendingMachineOpC
selectItem_VendingMachineOpC_min = 1
selectItem_VendingMachineOpC_max = 1
# dispenseItem_VendingMachineOpC
dispenseItem_VendingMachineOpC_min = 1
dispenseItem_VendingMachineOpC_max = 1

### Associations
# VendingMachineItem
VendingMachineItem_min = 4
VendingMachineItem_max = 4
# SnapshotItem
SnapshotItem_min = 4
SnapshotItem_max = 4
# SnapshotVendingMachine
SnapshotVendingMachine_min = 4
SnapshotVendingMachine_max = 4
# PredSuccVendingMachine
PredSuccVendingMachine_min = 3
PredSuccVendingMachine_max = 3
# PredSuccItem
PredSuccItem_min = 3
PredSuccItem_max = 3

aggregationcyclefreeness = on
forbiddensharing = on