[default]
Integer_min = 0
Integer_max = 100
String_max = 10
Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# Snapshot
Snapshot_min = 5
Snapshot_max = 5
# Filmstrip
Filmstrip_min = 4
Filmstrip_max = 4
# System
System_min = 5
System_max = 5
# Application
Application_min = 5
Application_max = 5

### Class Properties
# System - free_memory
#System_freeMemory_min = 0
#System_freeMemory_max = 15
#System_freeMemory: Set{10}
#System_loadedAppIds_min = -1
#System_loadedAppIds_max = -1
#System_loadedAppIds: Set{1, 2}
#System_installedAppIds_min = -1
#System_installedAppIds_max = -1
#System_installedAppIds: Set{1, 2}
# Application - size
#Application_size_min = 1
#Application_size_max = 5
#Application_size: Set{1, 2, 3}
#Application_id: Set{1, 2}

### Operation Classes
# load_SystemOpC
load_SystemOpC_min = 1
load_SystemOpC_max = 1
# install_SystemOpC
install_SystemOpC_min = 1
install_SystemOpC_max = 1
# run_SystemOpC
run_SystemOpC_min = 1
run_SystemOpC_max = 1
# stop_SystemOpC
stop_SystemOpC_min = 1
stop_SystemOpC_max = 1

### Association
# SnapshotSystem
SnapshotSystem_min = 5
SnapshotSystem_max = 5
# SnapshotApplication
SnapshotApplication_min = 5
SnapshotApplication_max = 5
# PredSucc System
PredSuccSystem_min = 4
PredSuccSystem_max = 4
# PredSucc Application
PredSuccApplication_min = 4
PredSuccApplication_max = 4
# SystemApplication
SystemApplication_min = 5
SystemApplication_max = 5

aggregationcyclefreeness = on
forbiddensharing = on