<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>use</artifactId>
		<groupId>org.tzi.use</groupId>
		<version>7.1.1</version>
	</parent>

	<artifactId>frsl</artifactId>
	<modelVersion>4.0.0</modelVersion>

	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>use-core</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>use-gui</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<sourceDirectory>src/main/java</sourceDirectory>

		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<release>21</release>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.2</version>

				<configuration>
					<archive>
						<manifestFile>src/main/resources/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>

			<plugin>
                <groupId>com.bekioui.maven.plugin</groupId>
                <artifactId>merge-maven-plugin</artifactId>
                <version>1.2.0</version>
                <executions>
                    <execution>
                        <id>merge-grammar-files</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>merge</goal>
                        </goals>
                        <configuration>
                            <merges>
                                <merge>
                                    <!-- Merge OCL grammar -->
                                    <target>${project.build.directory}/grammars/OCL.g</target>
                                    <sources>
                                        <source>src/main/resources/grammars/ocl/OCL.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLLexerRules.gpart</source>
                                    </sources>
                                    <override>true</override>
                                </merge>
                                <merge>
                                    <!-- Merge SOIL grammar -->
                                    <target>${project.build.directory}/grammars/Soil.g</target>
                                    <sources>
                                        <source>src/main/resources/grammars/soil/Soil.gpart</source>
                                        <source>src/main/resources/grammars/base/SoilBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLLexerRules.gpart</source>
                                    </sources>
                                    <override>true</override>
                                </merge>
                                <merge>
                                    <!-- Merge USE grammar -->
                                    <target>${project.build.directory}/grammars/USE.g</target>
                                    <sources>
                                        <source>src/main/resources/grammars/use/USE.gpart</source>
                                        <source>src/main/resources/grammars/base/USEBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLBase.gpart</source>
                                        <source>src/main/resources/grammars/base/SoilBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLLexerRules.gpart</source>
                                    </sources>
                                    <override>true</override>
                                </merge>
                                <merge>
                                    <!-- Merge Shell grammar -->
                                    <target>${project.build.directory}/grammars/ShellCommand.g</target>
                                    <sources>
                                        <source>src/main/resources/grammars/shell/ShellCommand.gpart</source>
                                        <source>
                                            src/main/resources/grammars/base/ShellCommandBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLBase.gpart</source>
                                        <source>src/main/resources/grammars/base/SoilBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLLexerRules.gpart</source>
                                    </sources>
                                    <override>true</override>
                                </merge>
                                <merge>
                                     Merge FRSL grammar 
                                    <target>${project.build.directory}/grammars/FRSL.g</target>
                                    <sources>
                                        <source>src/main/resources/grammars/frsl/FRSL.gpart</source>
                                        <source>src/main/resources/grammars/base/USEBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLBase.gpart</source>
                                        <source>src/main/resources/grammars/base/ShellCommandBase.gpart</source>
                                        <source>src/main/resources/grammars/base/SoilBase.gpart</source>
                                        <source>src/main/resources/grammars/base/OCLLexerRules.gpart</source>
                                    </sources>
                                    <override>true</override>
                                </merge>
                            </merges>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.antlr</groupId>
                <artifactId>antlr3-maven-plugin</artifactId>
                <version>3.5.3</version>
                <configuration>
                    <!--<debug>true</debug>-->
                    <!-- print some fancy information about the grammars-->
                    <report>false</report>
                    <!-- generated parser code will log rule entry and exit points to
                    stdout as an aid to debugging.-->
                    <trace>false</trace>
                    <!--   generate a dot graph of the NFA for each rule -->
                    <nfa>false</nfa>
                    <!-- generate a dot graph of the DFA for each decision in the grammar
                    -->
                    <dfa>false</dfa>
                    <sourceDirectory>target/grammars</sourceDirectory>
                    <verbose>false</verbose>
                </configuration>
                <executions>
                    <execution>
                        <id>antlr</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>antlr</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.coderplus.maven.plugins</groupId>
                <artifactId>copy-rename-maven-plugin</artifactId>
                <version>1.0.1</version>
                <executions>
                    <execution>
                        <id>move-antlr-parser-use</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>rename</goal>
                        </goals>
                        <configuration>
							<fileSets>
								<fileSet>
									<sourceFile>
										target/generated-sources/antlr3/FRSLLexer.java</sourceFile>
									<destinationFile>
										target/generated-sources/antlr3/org/vnu/sme/frsl/parser/FRSLLexer.java</destinationFile>
								</fileSet>
								<fileSet>
									<sourceFile>
										target/generated-sources/antlr3/FRSLParser.java</sourceFile>
									<destinationFile>
										target/generated-sources/antlr3/org/vnu/sme/frsl/parser/FRSLParser.java</destinationFile>
								</fileSet>							
                                <fileSet>
                                    <sourceFile>target/generated-sources/antlr3/USELexer.java</sourceFile>
                                    <destinationFile>
                                        ../tmp/USELexer.java</destinationFile>
                                </fileSet>
                                <fileSet>
                                    <sourceFile>target/generated-sources/antlr3/USEParser.java</sourceFile>
                                    <destinationFile>
                                        ../tmp/USEParser.java</destinationFile>
                                </fileSet>
                                <fileSet>
                                    <sourceFile>target/generated-sources/antlr3/OCLLexer.java</sourceFile>
                                    <destinationFile>
                                        ../tmp/OCLLexer.java</destinationFile>
                                </fileSet>
                                <fileSet>
                                    <sourceFile>target/generated-sources/antlr3/OCLParser.java</sourceFile>
                                    <destinationFile>
                                        ../tmp/OCLParser.java</destinationFile>
                                </fileSet>
                                <fileSet>
                                    <sourceFile>
                                        target/generated-sources/antlr3/ShellCommandLexer.java</sourceFile>
                                    <destinationFile>
                                        ../tmp/ShellCommandLexer.java</destinationFile>
                                </fileSet>
                                <fileSet>
                                    <sourceFile>
                                        target/generated-sources/antlr3/ShellCommandParser.java</sourceFile>
                                    <destinationFile>
                                        ../tmp/ShellCommandParser.java</destinationFile>
                                </fileSet>
                                <fileSet>
                                    <sourceFile>target/generated-sources/antlr3/SoilLexer.java</sourceFile>
                                    <destinationFile>
                                        ../tmp/SoilLexer.java</destinationFile>
                                </fileSet>
                                <fileSet>
                                    <sourceFile>target/generated-sources/antlr3/SoilParser.java</sourceFile>
                                    <destinationFile>
                                        ../tmp/SoilParser.java</destinationFile>
                                </fileSet>
                            </fileSets>
                        </configuration>
                    </execution>
                </executions>
			</plugin>  
		</plugins>
	</build>
</project>