[default]
Integer_min = 0
Integer_max = 100
String_max = 10
Real_min = -2.0
Real_max = 2.0
Real_step = 0.5

### Classes
# System
System_min = 1
System_max = 1
# Application
Application_min = 2
Application_max = 2

### Association
# SystemApplication
SystemApplication_min = 2
SystemApplication_max = 2

aggregationcyclefreeness = on
forbiddensharing = on